/* eslint-disable quote-props */

export const layoutsRoutesData = {
    'accordion-sample-1': { displayName: 'Accordion 1', parentName: 'Accordion' },
    'accordion-sample-2': { displayName: 'Accordion 2', parentName: 'Accordion' },
    'accordion-sample-3': { displayName: 'Accordion 3', parentName: 'Accordion' },
    'accordion-style': { displayName: 'Accordion Styling', parentName: 'Accordion' },
    'avatar-sample-1': { displayName: 'Avatar with Initials', parentName: 'Avatar' },
    'avatar-sample-2': { displayName: 'Avatar with Image', parentName: 'Avatar' },
    'avatar-sample-4': { displayName: 'Avatar with Icon', parentName: 'Avatar' },
    'avatar-sample-3': { displayName: 'Multiple avatars', parentName: 'Avatar' },
    'avatar-styling': { displayName: 'Styling avatars', parentName: 'Avatar' },
    'avatar-css-variables': { displayName: 'Avatar with CSS variables', parentName: 'Avatar' },
    'carousel': { displayName: 'Carousel Base', parentName: 'Carousel' },
    'carousel-no-navigation-sample': { displayName: 'Carousel No Navigation', parentName: 'Carousel' },
    'carousel-animations-sample': { displayName: 'Carousel Animations', parentName: 'Carousel' },
    'carousel-with-components-sample': { displayName: 'Carousel With Other Components', parentName: 'Carousel' },
    'carousel-tailwind-sample': { displayName: 'Carousel Tailwind', parentName: 'Carousel' },
    'carousel-styling-sample': { displayName: 'Carousel Styling', parentName: 'Carousel' },
    'dock-manager-sample': { displayName: 'Dock Manager', parentName: 'Dock Manager' },
    'expansion-sample-1': { displayName: 'Expansion Panel 1', parentName: 'Expansion Panel' },
    'expansion-sample-2': { displayName: 'Expansion Panel 2', parentName: 'Expansion Panel' },
    'expansion-sample-3': { displayName: 'Expansion Panel 3', parentName: 'Expansion Panel' },
    'expansion-sample-4': { displayName: 'Expansion Panel 4', parentName: 'Expansion Panel' },
    'expansion-sample-5': { displayName: 'Expansion Panel 5', parentName: 'Expansion Panel' },
    'expansion-styling': { displayName: 'Expansion Panel Styling', parentName: 'Expansion Panel' },
    'layout-direction-row': { displayName: 'Layout Direction Row', parentName: 'Layout' },
    'layout-direction-column': { displayName: 'Layout Direction Column', parentName: 'Layout' },
    'layout-custom-order': { displayName: 'Layout Custom Order', parentName: 'Layout' },
    'layout-content-space' : { displayName: 'Layout Content Space', parentName: 'Layout' },
    'layout-align-items' : { displayName: 'Layout Align Items', parentName: 'Layout' },
    'layout-justify-content' : { displayName: 'Layout Justify Content', parentName: 'Layout' },
    'layout-wrap' : { displayName: 'Layout Wrap', parentName: 'Layout' },
    'layout-sample' : { displayName: 'Layouts Sample', parentName: 'Layout' },
    'splitter-collapsible-sample': { displayName: 'Splitter Collapsible', parentName: 'Splitter' },
    'splitter-horizontal-sample': { displayName: 'Splitter Horizontal', parentName: 'Splitter' },
    'splitter-nested-sample': { displayName: 'Splitter Nested Panes', parentName: 'Splitter' },
    'splitter-styling-sample': { displayName: 'Splitter Styling', parentName: 'Splitter' },
    'stepper-overview-sample': { displayName: 'Stepper Overview', parentName: 'Stepper' },
    'stepper-sample-reactive-forms': { displayName: 'Stepper Reactive Forms', parentName: 'Stepper' },
    'stepper-label-position-and-orientation-sample': { displayName: 'Stepper Label Position And Orientation', parentName: 'Stepper' },
    'stepper-linear-sample': { displayName: 'Linear Stepper', parentName: 'Stepper' },
    'stepper-steptypes-sample': { displayName: 'Stepper Step Types', parentName: 'Stepper' },
    'stepper-styling-sample': { displayName: 'Stepper Styling', parentName: 'Stepper' },
    'tabbar-sample-1': { displayName: 'Bottom Navigation Simple Panels', parentName: 'Bottom Navigation' },
    'tabbar-sample-2': { displayName: 'Bottom Navigation Customizing Panels', parentName: 'Bottom Navigation' },
    'tabbar-sample-3': { displayName: 'Bottom Navigation Routing', parentName: 'Bottom Navigation' },
    'tabbar-style': { displayName: 'Bottom Navigation Styling', parentName: 'Bottom Navigation' },
    'tabs-sample-1': { displayName: 'Tabs Overview', parentName: 'Tabs' },
    'tabs-sample-2': { displayName: 'Tabs Types', parentName: 'Tabs' },
    'tabs-sample-3': { displayName: 'Tabs Customizing', parentName: 'Tabs' },
    'tabs-sample-4': { displayName: 'Tabs Routing', parentName: 'Tabs' },
    'tabs-style': { displayName: 'Tabs Styling', parentName: 'Tabs' },
    'tabs-alignment': { displayName: 'Tabs Alignment', parentName: 'Tabs' },
    'tabs-header-prefix-suffix': { displayName: 'Tabs Prefix/Suffix', parentName: 'Tabs' },
    'card-sample-0': { displayName: 'Elevated Card', parentName: 'Card' },
    'card-sample-1': { displayName: 'Outlined Card', parentName: 'Card' },
    'card-sample-2': { displayName: 'Horizontal Card', parentName: 'Card' },
    'card-sample-3': { displayName: 'Horizontal Card Alt', parentName: 'Card' },
    'card-sample-4': { displayName: 'Other Examples', parentName: 'Card' },
    'card-styling-sample': { displayName: 'Styled Card', parentName: 'Card' },
    'divider-sample-1': { displayName: 'Default Divider', parentName: 'Divider' },
    'divider-sample-2': { displayName: 'Vertical Divider', parentName: 'Divider' },
    'divider-sample-3': { displayName: 'Dashed Divider', parentName: 'Divider' },
    'divider-sample-4': { displayName: 'Inset Divider', parentName: 'Divider' },
    'tile-manager-sample': { displayName: 'Tile Manager Overview', parentName: 'Tile Manager' }
}
