export const LOCAL_DATA = [
    {
    CategoryID: 1,
    Discontinued: false,
    OrderDate: "07/25/2012",
    ProductID: 1,
    ProductName: "Chai",
    QuantityPerUnit: "10 boxes x 20 bags",
    ReorderLevel: 10,
    SupplierID: 1,
    UnitPrice: "18.0000",
    UnitsInStock: 39,
    UnitsOnOrder: 0
    }, {
    CategoryID: 1,
    Discontinued: false,
    OrderDate: "03/17/2003",
    ProductID: 2,
    ProductName: "Chang",
    QuantityPerUnit: "24 - 12 oz bottles",
    ReorderLevel: 25,
    SupplierID: 1,
    UnitPrice: "19.0000",
    UnitsInStock: 17,
    UnitsOnOrder: 40
    }, {
    CategoryID: 2,
    Discontinued: false,
    OrderDate: "03/17/2006",
    ProductID: 3,
    ProductName: "Aniseed Syrup",
    QuantityPerUnit: "12 - 550 ml bottles",
    ReorderLevel: 25,
    SupplierID: 1,
    UnitPrice: "10.0000",
    UnitsInStock: 13,
    UnitsOnOrder: 70
    }, {
    CategoryID: 2,
    Discontinued: false,
    OrderDate: "07/17/2020",
    ProductID: 4,
    ProductName: "Chef Antons Cajun Seasoning",
    QuantityPerUnit: "48 - 6 oz jars",
    ReorderLevel: 0,
    SupplierID: 2,
    UnitPrice: "22.0000",
    UnitsInStock: 53,
    UnitsOnOrder: 0
    }, {
    CategoryID: 2,
    Discontinued: true,
    OrderDate: "11/11/2011",
    ProductID: 5,
    ProductName: "Chef Antons Gumbo Mix",
    QuantityPerUnit: "36 boxes",
    ReorderLevel: 0,
    SupplierID: 2,
    UnitPrice: "21.3500",
    UnitsInStock: 0,
    UnitsOnOrder: 0
    }, {
    CategoryID: 2,
    Discontinued: false,
    OrderDate: "12/17/2007",
    ProductID: 6,
    ProductName: "Grandmas Boysenberry Spread",
    QuantityPerUnit: "12 - 8 oz jars",
    ReorderLevel: 25,
    SupplierID: 3,
    UnitPrice: "25.0000",
    UnitsInStock: 0,
    UnitsOnOrder: 0
    }, {
    CategoryID: 7,
    Discontinued: false,
    OrderDate: "12/17/2016",
    ProductID: 7,
    ProductName: "Uncle Bobs Organic Dried Pears",
    QuantityPerUnit: "12 - 1 lb pkgs.",
    ReorderLevel: 10,
    SupplierID: 3,
    UnitPrice: "30.0000",
    UnitsInStock: 150,
    UnitsOnOrder: 0
    }, {
    CategoryID: 2,
    Discontinued: false,
    OrderDate: "01/17/2025",
    ProductID: 8,
    ProductName: "Northwoods Cranberry Sauce",
    QuantityPerUnit: "12 - 12 oz jars",
    ReorderLevel: 0,
    SupplierID: 3,
    UnitPrice: "40.0000",
    UnitsInStock: 6,
    UnitsOnOrder: 0
    }, {
    CategoryID: 6,
    Discontinued: true,
    OrderDate: "02/17/2010",
    ProductID: 9,
    ProductName: "Chips",
    QuantityPerUnit: "18 - 500 g pkgs.",
    ReorderLevel: 0,
    SupplierID: 4,
    UnitPrice: "7.0000",
    UnitsInStock: 29,
    UnitsOnOrder: 0
    }, {
    CategoryID: 8,
    Discontinued: false,
    OrderDate: "05/27/2008",
    ProductID: 10,
    ProductName: "Dulce de Leche",
    QuantityPerUnit: "12 - 200 ml jars",
    ReorderLevel: 0,
    SupplierID: 4,
    UnitPrice: "91.0000",
    UnitsInStock: 31,
    UnitsOnOrder: 0
    }, {
    CategoryID: 4,
    Discontinued: false,
    OrderDate: "01/01/2009",
    ProductID: 11,
    ProductName: "Queso Cabrales",
    QuantityPerUnit: "1 kg pkg.",
    ReorderLevel: 30,
    SupplierID: 5,
    UnitPrice: "21.0000",
    UnitsInStock: 22,
    UnitsOnOrder: 30
    }, {
    CategoryID: 4,
    Discontinued: false,
    OrderDate: "11/17/2012",
    ProductID: 12,
    ProductName: "Queso Manchego La Pastora",
    QuantityPerUnit: "10 - 500 g pkgs.",
    ReorderLevel: 0,
    SupplierID: 5,
    UnitPrice: "38.0000",
    UnitsInStock: 86,
    UnitsOnOrder: 0
    }, {
    CategoryID: 8,
    Discontinued: false,
    OrderDate: "05/19/2013",
    ProductID: 13,
    ProductName: "Chocolate",
    QuantityPerUnit: "2 kg box",
    ReorderLevel: 5,
    SupplierID: 6,
    UnitPrice: "96.0000",
    UnitsInStock: 24,
    UnitsOnOrder: 0
    }, {
    CategoryID: 7,
    Discontinued: false,
    OrderDate: "06/17/2016",
    ProductID: 14,
    ProductName: "Tofu",
    QuantityPerUnit: "40 - 100 g pkgs.",
    ReorderLevel: 0,
    SupplierID: 6,
    UnitPrice: "23.2500",
    UnitsInStock: 35,
    UnitsOnOrder: 0
    }, {
    CategoryID: 2,
    Discontinued: false,
    OrderDate: "12/12/2012",
    ProductID: 15,
    ProductName: "Yogurt",
    QuantityPerUnit: "24 - 250 ml bottles",
    ReorderLevel: 5,
    SupplierID: 6,
    UnitPrice: "15.5000",
    UnitsInStock: 39,
    UnitsOnOrder: 0
    }, {
    CategoryID: 3,
    Discontinued: false,
    OrderDate: "07/17/2007",
    ProductID: 16,
    ProductName: "Pavlova",
    QuantityPerUnit: "32 - 500 g boxes",
    ReorderLevel: 10,
    SupplierID: 7,
    UnitPrice: "17.4500",
    UnitsInStock: 29,
    UnitsOnOrder: 0
    }, {
    CategoryID: 6,
    Discontinued: true,
    OrderDate: "11/21/2021",
    ProductID: 17,
    ProductName: "Alice Mutton",
    QuantityPerUnit: "20 - 1 kg tins",
    ReorderLevel: 0,
    SupplierID: 7,
    UnitPrice: "39.0000",
    UnitsInStock: 0,
    UnitsOnOrder: 0
    }, {
    CategoryID: 8,
    Discontinued: false,
    OrderDate: "10/13/2014",
    ProductID: 18,
    ProductName: "Carnarvon Tigers",
    QuantityPerUnit: "16 kg pkg.",
    ReorderLevel: 0,
    SupplierID: 7,
    UnitPrice: "62.5000",
    UnitsInStock: 42,
    UnitsOnOrder: 0
    }, {
    CategoryID: 3,
    Discontinued: false,
    OrderDate: "12/15/1995",
    ProductID: 19,
    ProductName: "Teatime Chocolate Biscuits",
    QuantityPerUnit: "",
    ReorderLevel: 5,
    SupplierID: 8,
    UnitPrice: "9.2000",
    UnitsInStock: 25,
    UnitsOnOrder: 0
    }, {
    CategoryID: 3,
    Discontinued: false,
    OrderDate: "12/17/2001",
    ProductID: 20,
    ProductName: "Sir Rodneys Marmalade",
    QuantityPerUnit: "",
    ReorderLevel: 0,
    SupplierID: 8,
    UnitPrice: "19.9000",
    UnitsInStock: 40,
    UnitsOnOrder: 0
    }
];
