export const athletesData = [
    {
      'Id': 269,
      'Avatar': 'https://randomuser.me/api/portraits/men/4.jpg',
      'Position': 'up',
      'Name': 'Pennington Munoz',
      'AthleteNumber': 47199,
      'BeatsPerMinute': 94,
      'TopSpeed': 4.4,
      'Registered': '2017-08-07T04:26:28 -03:00',
      'TrackProgress': 42,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/AF.png',
      'CountryName': 'Afghanistan'
    },
    {
      'Id': 101,
      'Avatar': 'https://randomuser.me/api/portraits/men/30.jpg',
      'Position': 'down',
      'Name': 'Lynette Vaughan',
      'AthleteNumber': 39958,
      'BeatsPerMinute': 92,
      'TopSpeed': 4.1,
      'Registered': '2017-07-29T11:45:41 -03:00',
      'TrackProgress': 45,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/AL.png',
      'CountryName': 'Albania'
    },
    {
      'Id': 134,
      'Avatar': 'https://randomuser.me/api/portraits/men/1.jpg',
      'Position': 'down',
      'Name': 'Arnold Cruz',
      'AthleteNumber': 20723,
      'BeatsPerMinute': 104,
      'TopSpeed': 4.4,
      'Registered': '2017-10-24T10:59:28 -03:00',
      'TrackProgress': 30,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/DZ.png',
      'CountryName': 'Algeria'
    },
    {
      'Id': 443,
      'Avatar': 'https://randomuser.me/api/portraits/men/3.jpg',
      'Position': 'up',
      'Name': 'Duran Stark',
      'AthleteNumber': 46704,
      'BeatsPerMinute': 105,
      'TopSpeed': 4.3,
      'Registered': '2017-07-02T03:51:14 -03:00',
      'TrackProgress': 24,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/AD.png',
      'CountryName': 'AndorrA'
    },
    {
      'Id': 494,
      'Avatar': 'https://randomuser.me/api/portraits/men/49.jpg',
      'Position': 'down',
      'Name': 'Kidd Stone',
      'AthleteNumber': 31398,
      'BeatsPerMinute': 90,
      'TopSpeed': 5.4,
      'Registered': '2017-10-19T11:31:06 -03:00',
      'TrackProgress': 42,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/AO.png',
      'CountryName': 'Angola'
    },
    {
      'Id': 471,
      'Avatar': 'https://randomuser.me/api/portraits/men/27.jpg',
      'Position': 'down',
      'Name': 'Joan Adams',
      'AthleteNumber': 46698,
      'BeatsPerMinute': 100,
      'TopSpeed': 5.7,
      'Registered': '2017-03-25T09:53:07 -02:00',
      'TrackProgress': 33,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/AG.png',
      'CountryName': 'Antigua and Barbuda'
    },
    {
      'Id': 367,
      'Avatar': 'https://randomuser.me/api/portraits/men/43.jpg',
      'Position': 'current',
      'Name': 'Dillard Nunez',
      'AthleteNumber': 29859,
      'BeatsPerMinute': 96,
      'TopSpeed': 4.1,
      'Registered': '2017-03-08T09:15:43 -02:00',
      'TrackProgress': 46,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/AR.png',
      'CountryName': 'Argentina'
    },
    {
      'Id': 121,
      'Avatar': 'https://randomuser.me/api/portraits/men/3.jpg',
      'Position': 'down',
      'Name': 'Bettye Erickson',
      'AthleteNumber': 39591,
      'BeatsPerMinute': 95,
      'TopSpeed': 4.3,
      'Registered': '2017-01-29T06:15:30 -02:00',
      'TrackProgress': 42,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/AM.png',
      'CountryName': 'Armenia'
    },
    {
      'Id': 98,
      'Avatar': 'https://randomuser.me/api/portraits/men/43.jpg',
      'Position': 'down',
      'Name': 'Beth Stanley',
      'AthleteNumber': 25111,
      'BeatsPerMinute': 108,
      'TopSpeed': 5.3,
      'Registered': '2017-06-05T04:21:51 -03:00',
      'TrackProgress': 30,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/AU.png',
      'CountryName': 'Australia'
    },
    {
      'Id': 78,
      'Avatar': 'https://randomuser.me/api/portraits/men/5.jpg',
      'Position': 'current',
      'Name': 'Marquita Larson',
      'AthleteNumber': 35334,
      'BeatsPerMinute': 99,
      'TopSpeed': 5.6,
      'Registered': '2017-04-25T08:59:17 -03:00',
      'TrackProgress': 23,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/AT.png',
      'CountryName': 'Austria'
    },
    {
      'Id': 344,
      'Avatar': 'https://randomuser.me/api/portraits/men/40.jpg',
      'Position': 'up',
      'Name': 'Jillian Colon',
      'AthleteNumber': 25597,
      'BeatsPerMinute': 107,
      'TopSpeed': 5.9,
      'Registered': '2017-06-24T08:00:30 -03:00',
      'TrackProgress': 25,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/AZ.png',
      'CountryName': 'Azerbaijan'
    },
    {
      'Id': 229,
      'Avatar': 'https://randomuser.me/api/portraits/men/6.jpg',
      'Position': 'down',
      'Name': 'Cross Barlow',
      'AthleteNumber': 25443,
      'BeatsPerMinute': 105,
      'TopSpeed': 4.3,
      'Registered': '2017-10-20T01:30:16 -03:00',
      'TrackProgress': 42,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/BS.png',
      'CountryName': 'Bahamas'
    },
    {
      'Id': 402,
      'Avatar': 'https://randomuser.me/api/portraits/men/6.jpg',
      'Position': 'current',
      'Name': 'Marion Trujillo',
      'AthleteNumber': 36064,
      'BeatsPerMinute': 110,
      'TopSpeed': 4.5,
      'Registered': '2017-01-26T01:59:12 -02:00',
      'TrackProgress': 41,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/BH.png',
      'CountryName': 'Bahrain'
    },
    {
      'Id': 308,
      'Avatar': 'https://randomuser.me/api/portraits/men/27.jpg',
      'Position': 'current',
      'Name': 'Kenya Montgomery',
      'AthleteNumber': 27538,
      'BeatsPerMinute': 110,
      'TopSpeed': 5.2,
      'Registered': '2017-02-24T11:22:02 -02:00',
      'TrackProgress': 28,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/BD.png',
      'CountryName': 'Bangladesh'
    },
    {
      'Id': 228,
      'Avatar': 'https://randomuser.me/api/portraits/men/6.jpg',
      'Position': 'down',
      'Name': 'Juarez Stokes',
      'AthleteNumber': 33620,
      'BeatsPerMinute': 104,
      'TopSpeed': 4.4,
      'Registered': '2017-07-20T04:30:43 -03:00',
      'TrackProgress': 30,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/BB.png',
      'CountryName': 'Barbados'
    },
    {
      'Id': 306,
      'Avatar': 'https://randomuser.me/api/portraits/men/32.jpg',
      'Position': 'down',
      'Name': 'Justice Juarez',
      'AthleteNumber': 38181,
      'BeatsPerMinute': 108,
      'TopSpeed': 5.2,
      'Registered': '2017-08-23T02:05:38 -03:00',
      'TrackProgress': 48,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/BY.png',
      'CountryName': 'Belarus'
    },
    {
      'Id': 494,
      'Avatar': 'https://randomuser.me/api/portraits/men/26.jpg',
      'Position': 'down',
      'Name': 'Alston Booth',
      'AthleteNumber': 38581,
      'BeatsPerMinute': 99,
      'TopSpeed': 4.3,
      'Registered': '2017-06-26T12:38:14 -03:00',
      'TrackProgress': 37,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/BE.png',
      'CountryName': 'Belgium'
    },
    {
      'Id': 46,
      'Avatar': 'https://randomuser.me/api/portraits/men/11.jpg',
      'Position': 'down',
      'Name': 'Gertrude Savage',
      'AthleteNumber': 13356,
      'BeatsPerMinute': 96,
      'TopSpeed': 5,
      'Registered': '2017-06-04T09:36:23 -03:00',
      'TrackProgress': 38,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/BZ.png',
      'CountryName': 'Belize'
    },
    {
      'Id': 15,
      'Avatar': 'https://randomuser.me/api/portraits/men/11.jpg',
      'Position': 'current',
      'Name': 'Harvey Lancaster',
      'AthleteNumber': 44841,
      'BeatsPerMinute': 90,
      'TopSpeed': 4.4,
      'Registered': '2017-05-13T04:08:23 -03:00',
      'TrackProgress': 23,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/BJ.png',
      'CountryName': 'Benin'
    },
    {
      'Id': 354,
      'Avatar': 'https://randomuser.me/api/portraits/men/47.jpg',
      'Position': 'down',
      'Name': 'Greer Mullen',
      'AthleteNumber': 39557,
      'BeatsPerMinute': 101,
      'TopSpeed': 4.3,
      'Registered': '2017-10-08T01:36:49 -03:00',
      'TrackProgress': 41,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/BT.png',
      'CountryName': 'Bhutan'
    },
    {
      'Id': 566,
      'Avatar': 'https://randomuser.me/api/portraits/men/49.jpg',
      'Position': 'current',
      'Name': 'Ava Yang',
      'AthleteNumber': 31918,
      'BeatsPerMinute': 99,
      'TopSpeed': 5.2,
      'Registered': '2017-08-24T06:04:56 -03:00',
      'TrackProgress': 35,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/BO.png',
      'CountryName': 'Bolivia'
    },
    {
      'Id': 23,
      'Avatar': 'https://randomuser.me/api/portraits/men/46.jpg',
      'Position': 'up',
      'Name': 'Blanche Yates',
      'AthleteNumber': 49389,
      'BeatsPerMinute': 104,
      'TopSpeed': 5.4,
      'Registered': '2017-07-30T09:53:40 -03:00',
      'TrackProgress': 47,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/BA.png',
      'CountryName': 'Bosnia and Herzegovina'
    },
    {
      'Id': 536,
      'Avatar': 'https://randomuser.me/api/portraits/men/50.jpg',
      'Position': 'current',
      'Name': 'Foreman Schroeder',
      'AthleteNumber': 17234,
      'BeatsPerMinute': 106,
      'TopSpeed': 4.5,
      'Registered': '2017-03-29T03:07:02 -03:00',
      'TrackProgress': 34,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/BW.png',
      'CountryName': 'Botswana'
    },
    {
      'Id': 320,
      'Avatar': 'https://randomuser.me/api/portraits/men/19.jpg',
      'Position': 'up',
      'Name': 'Lancaster Reeves',
      'AthleteNumber': 34219,
      'BeatsPerMinute': 98,
      'TopSpeed': 4.5,
      'Registered': '2017-02-17T03:46:33 -02:00',
      'TrackProgress': 44,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/BR.png',
      'CountryName': 'Brazil'
    },
    {
      'Id': 160,
      'Avatar': 'https://randomuser.me/api/portraits/men/8.jpg',
      'Position': 'up',
      'Name': 'Monica Estes',
      'AthleteNumber': 49339,
      'BeatsPerMinute': 96,
      'TopSpeed': 5.4,
      'Registered': '2017-04-02T05:20:42 -03:00',
      'TrackProgress': 31,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/BN.png',
      'CountryName': 'Brunei Darussalam'
    },
    {
      'Id': 579,
      'Avatar': 'https://randomuser.me/api/portraits/men/20.jpg',
      'Position': 'up',
      'Name': 'Lakisha Deleon',
      'AthleteNumber': 48048,
      'BeatsPerMinute': 98,
      'TopSpeed': 4.7,
      'Registered': '2017-06-03T05:01:56 -03:00',
      'TrackProgress': 36,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/BG.png',
      'CountryName': 'Bulgaria'
    },
    {
      'Id': 342,
      'Avatar': 'https://randomuser.me/api/portraits/men/33.jpg',
      'Position': 'down',
      'Name': 'Barbra Gonzalez',
      'AthleteNumber': 39886,
      'BeatsPerMinute': 107,
      'TopSpeed': 5.6,
      'Registered': '2017-10-02T02:34:44 -03:00',
      'TrackProgress': 48,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/BF.png',
      'CountryName': 'Burkina Faso'
    },
    {
      'Id': 397,
      'Avatar': 'https://randomuser.me/api/portraits/men/42.jpg',
      'Position': 'down',
      'Name': 'Hansen Dean',
      'AthleteNumber': 37400,
      'BeatsPerMinute': 96,
      'TopSpeed': 4.1,
      'Registered': '2017-09-04T05:27:16 -03:00',
      'TrackProgress': 35,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/BI.png',
      'CountryName': 'Burundi'
    },
    {
      'Id': 548,
      'Avatar': 'https://randomuser.me/api/portraits/men/9.jpg',
      'Position': 'down',
      'Name': 'Marcie Woods',
      'AthleteNumber': 43735,
      'BeatsPerMinute': 92,
      'TopSpeed': 4.2,
      'Registered': '2017-10-07T11:54:23 -03:00',
      'TrackProgress': 36,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/KH.png',
      'CountryName': 'Cambodia'
    },
    {
      'Id': 292,
      'Avatar': 'https://randomuser.me/api/portraits/men/30.jpg',
      'Position': 'current',
      'Name': 'Rivas Wilder',
      'AthleteNumber': 36991,
      'BeatsPerMinute': 110,
      'TopSpeed': 4.4,
      'Registered': '2017-07-20T10:10:26 -03:00',
      'TrackProgress': 20,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/CM.png',
      'CountryName': 'Cameroon'
    },
    {
      'Id': 389,
      'Avatar': 'https://randomuser.me/api/portraits/men/19.jpg',
      'Position': 'down',
      'Name': 'Margie Rocha',
      'AthleteNumber': 22009,
      'BeatsPerMinute': 95,
      'TopSpeed': 5.8,
      'Registered': '2017-07-17T01:24:41 -03:00',
      'TrackProgress': 20,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/CA.png',
      'CountryName': 'Canada'
    },
    {
      'Id': 478,
      'Avatar': 'https://randomuser.me/api/portraits/men/42.jpg',
      'Position': 'down',
      'Name': 'Dunlap Hart',
      'AthleteNumber': 18492,
      'BeatsPerMinute': 93,
      'TopSpeed': 5.5,
      'Registered': '2017-08-10T05:20:52 -03:00',
      'TrackProgress': 40,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/CV.png',
      'CountryName': 'Cape Verde'
    },
    {
      'Id': 544,
      'Avatar': 'https://randomuser.me/api/portraits/men/31.jpg',
      'Position': 'up',
      'Name': 'Luella Rush',
      'AthleteNumber': 40897,
      'BeatsPerMinute': 110,
      'TopSpeed': 5,
      'Registered': '2017-07-26T11:22:42 -03:00',
      'TrackProgress': 25,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/CF.png',
      'CountryName': 'Central African Republic'
    },
    {
      'Id': 77,
      'Avatar': 'https://randomuser.me/api/portraits/men/9.jpg',
      'Position': 'current',
      'Name': 'Alvarado Justice',
      'AthleteNumber': 46671,
      'BeatsPerMinute': 109,
      'TopSpeed': 4.7,
      'Registered': '2017-05-27T08:13:51 -03:00',
      'TrackProgress': 49,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/TD.png',
      'CountryName': 'Chad'
    },
    {
      'Id': 210,
      'Avatar': 'https://randomuser.me/api/portraits/men/45.jpg',
      'Position': 'current',
      'Name': 'Jones Contreras',
      'AthleteNumber': 46829,
      'BeatsPerMinute': 93,
      'TopSpeed': 4.7,
      'Registered': '2017-10-31T05:44:58 -02:00',
      'TrackProgress': 46,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/CL.png',
      'CountryName': 'Chile'
    },
    {
      'Id': 384,
      'Avatar': 'https://randomuser.me/api/portraits/men/16.jpg',
      'Position': 'up',
      'Name': 'Vaughn Carroll',
      'AthleteNumber': 36161,
      'BeatsPerMinute': 95,
      'TopSpeed': 5.6,
      'Registered': '2017-04-04T06:59:25 -03:00',
      'TrackProgress': 33,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/CN.png',
      'CountryName': 'China'
    },
    {
      'Id': 532,
      'Avatar': 'https://randomuser.me/api/portraits/men/43.jpg',
      'Position': 'current',
      'Name': 'Cornelia Boyle',
      'AthleteNumber': 29617,
      'BeatsPerMinute': 107,
      'TopSpeed': 4.1,
      'Registered': '2017-07-15T04:50:40 -03:00',
      'TrackProgress': 39,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/CO.png',
      'CountryName': 'Colombia'
    },
    {
      'Id': 111,
      'Avatar': 'https://randomuser.me/api/portraits/men/43.jpg',
      'Position': 'current',
      'Name': 'Kimberly Becker',
      'AthleteNumber': 48138,
      'BeatsPerMinute': 101,
      'TopSpeed': 4.2,
      'Registered': '2017-06-02T09:21:56 -03:00',
      'TrackProgress': 41,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/KM.png',
      'CountryName': 'Comoros'
    },
    {
      'Id': 555,
      'Avatar': 'https://randomuser.me/api/portraits/men/3.jpg',
      'Position': 'current',
      'Name': 'Alma Vaughn',
      'AthleteNumber': 15147,
      'BeatsPerMinute': 102,
      'TopSpeed': 5.4,
      'Registered': '2017-09-25T03:06:39 -03:00',
      'TrackProgress': 39,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/CG.png',
      'CountryName': 'Congo'
    },
    {
      'Id': 565,
      'Avatar': 'https://randomuser.me/api/portraits/men/21.jpg',
      'Position': 'up',
      'Name': 'Bonnie Conway',
      'AthleteNumber': 32697,
      'BeatsPerMinute': 91,
      'TopSpeed': 5.8,
      'Registered': '2017-08-02T10:02:39 -03:00',
      'TrackProgress': 49,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/CD.png',
      'CountryName': 'Congo, The Democratic Republic of the'
    },
    {
      'Id': 571,
      'Avatar': 'https://randomuser.me/api/portraits/men/45.jpg',
      'Position': 'up',
      'Name': 'Ewing Mckenzie',
      'AthleteNumber': 41874,
      'BeatsPerMinute': 106,
      'TopSpeed': 4.6,
      'Registered': '2017-01-12T07:50:20 -02:00',
      'TrackProgress': 38,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/CK.png',
      'CountryName': 'Cook Islands'
    },
    {
      'Id': 204,
      'Avatar': 'https://randomuser.me/api/portraits/men/1.jpg',
      'Position': 'up',
      'Name': 'Kim Maldonado',
      'AthleteNumber': 32110,
      'BeatsPerMinute': 94,
      'TopSpeed': 5.1,
      'Registered': '2017-08-30T05:36:32 -03:00',
      'TrackProgress': 49,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/CR.png',
      'CountryName': 'Costa Rica'
    },
    {
      'Id': 99,
      'Avatar': 'https://randomuser.me/api/portraits/men/28.jpg',
      'Position': 'down',
      'Name': 'Reva Thornton',
      'AthleteNumber': 29846,
      'BeatsPerMinute': 105,
      'TopSpeed': 5.9,
      'Registered': '2017-10-05T05:47:28 -03:00',
      'TrackProgress': 49,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/CI.png',
      'CountryName': 'Cote DIvoire'
    },
    {
      'Id': 290,
      'Avatar': 'https://randomuser.me/api/portraits/men/31.jpg',
      'Position': 'up',
      'Name': 'Hendrix Gardner',
      'AthleteNumber': 16208,
      'BeatsPerMinute': 105,
      'TopSpeed': 5.1,
      'Registered': '2017-10-23T12:48:02 -03:00',
      'TrackProgress': 50,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/HR.png',
      'CountryName': 'Croatia'
    },
    {
      'Id': 117,
      'Avatar': 'https://randomuser.me/api/portraits/men/50.jpg',
      'Position': 'current',
      'Name': 'Drake Mclaughlin',
      'AthleteNumber': 26574,
      'BeatsPerMinute': 93,
      'TopSpeed': 4.1,
      'Registered': '2017-02-13T01:22:37 -02:00',
      'TrackProgress': 41,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/CU.png',
      'CountryName': 'Cuba'
    },
    {
      'Id': 119,
      'Avatar': 'https://randomuser.me/api/portraits/men/18.jpg',
      'Position': 'current',
      'Name': 'England Brady',
      'AthleteNumber': 19565,
      'BeatsPerMinute': 97,
      'TopSpeed': 4.4,
      'Registered': '2017-08-24T12:39:03 -03:00',
      'TrackProgress': 40,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/CY.png',
      'CountryName': 'Cyprus'
    },
    {
      'Id': 339,
      'Avatar': 'https://randomuser.me/api/portraits/men/31.jpg',
      'Position': 'current',
      'Name': 'Odonnell Hahn',
      'AthleteNumber': 20573,
      'BeatsPerMinute': 102,
      'TopSpeed': 4.6,
      'Registered': '2017-05-24T08:37:13 -03:00',
      'TrackProgress': 45,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/CZ.png',
      'CountryName': 'Czech Republic'
    },
    {
      'Id': 66,
      'Avatar': 'https://randomuser.me/api/portraits/men/27.jpg',
      'Position': 'up',
      'Name': 'Concetta Shannon',
      'AthleteNumber': 45319,
      'BeatsPerMinute': 91,
      'TopSpeed': 4.5,
      'Registered': '2017-03-02T01:44:58 -02:00',
      'TrackProgress': 25,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/DK.png',
      'CountryName': 'Denmark'
    },
    {
      'Id': 87,
      'Avatar': 'https://randomuser.me/api/portraits/men/33.jpg',
      'Position': 'up',
      'Name': 'Mcclure Lloyd',
      'AthleteNumber': 14594,
      'BeatsPerMinute': 98,
      'TopSpeed': 4.2,
      'Registered': '2017-06-19T02:57:10 -03:00',
      'TrackProgress': 31,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/DJ.png',
      'CountryName': 'Djibouti'
    },
    {
      'Id': 110,
      'Avatar': 'https://randomuser.me/api/portraits/men/34.jpg',
      'Position': 'current',
      'Name': 'Pickett Emerson',
      'AthleteNumber': 29420,
      'BeatsPerMinute': 94,
      'TopSpeed': 5.7,
      'Registered': '2017-10-18T10:26:13 -03:00',
      'TrackProgress': 35,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/DM.png',
      'CountryName': 'Dominica'
    },
    {
      'Id': 68,
      'Avatar': 'https://randomuser.me/api/portraits/men/48.jpg',
      'Position': 'current',
      'Name': 'Holloway Pollard',
      'AthleteNumber': 17354,
      'BeatsPerMinute': 98,
      'TopSpeed': 4.3,
      'Registered': '2017-01-09T08:20:50 -02:00',
      'TrackProgress': 45,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/DO.png',
      'CountryName': 'Dominican Republic'
    },
    {
      'Id': 96,
      'Avatar': 'https://randomuser.me/api/portraits/men/7.jpg',
      'Position': 'down',
      'Name': 'Shirley Young',
      'AthleteNumber': 43279,
      'BeatsPerMinute': 109,
      'TopSpeed': 4.2,
      'Registered': '2017-05-25T02:30:07 -03:00',
      'TrackProgress': 21,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/EC.png',
      'CountryName': 'Ecuador'
    },
    {
      'Id': 14,
      'Avatar': 'https://randomuser.me/api/portraits/men/49.jpg',
      'Position': 'current',
      'Name': 'Kay Jacobs',
      'AthleteNumber': 16116,
      'BeatsPerMinute': 102,
      'TopSpeed': 5.1,
      'Registered': '2017-08-13T04:10:16 -03:00',
      'TrackProgress': 30,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/EG.png',
      'CountryName': 'Egypt'
    },
    {
      'Id': 492,
      'Avatar': 'https://randomuser.me/api/portraits/men/8.jpg',
      'Position': 'up',
      'Name': 'Arline Warren',
      'AthleteNumber': 41011,
      'BeatsPerMinute': 102,
      'TopSpeed': 5.4,
      'Registered': '2017-08-20T12:48:35 -03:00',
      'TrackProgress': 29,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/SV.png',
      'CountryName': 'El Salvador'
    },
    {
      'Id': 458,
      'Avatar': 'https://randomuser.me/api/portraits/men/34.jpg',
      'Position': 'down',
      'Name': 'Solomon Golden',
      'AthleteNumber': 45847,
      'BeatsPerMinute': 102,
      'TopSpeed': 5.3,
      'Registered': '2017-05-27T01:35:39 -03:00',
      'TrackProgress': 21,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/GQ.png',
      'CountryName': 'Equatorial Guinea'
    },
    {
      'Id': 212,
      'Avatar': 'https://randomuser.me/api/portraits/men/8.jpg',
      'Position': 'down',
      'Name': 'Dolly Vincent',
      'AthleteNumber': 19047,
      'BeatsPerMinute': 90,
      'TopSpeed': 4.7,
      'Registered': '2017-09-11T08:38:25 -03:00',
      'TrackProgress': 22,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/ER.png',
      'CountryName': 'Eritrea'
    },
    {
      'Id': 113,
      'Avatar': 'https://randomuser.me/api/portraits/men/12.jpg',
      'Position': 'down',
      'Name': 'Young Callahan',
      'AthleteNumber': 23519,
      'BeatsPerMinute': 100,
      'TopSpeed': 4.4,
      'Registered': '2017-03-16T08:04:30 -02:00',
      'TrackProgress': 47,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/EE.png',
      'CountryName': 'Estonia'
    },
    {
      'Id': 412,
      'Avatar': 'https://randomuser.me/api/portraits/men/22.jpg',
      'Position': 'current',
      'Name': 'Lillie Gentry',
      'AthleteNumber': 34851,
      'BeatsPerMinute': 106,
      'TopSpeed': 4.9,
      'Registered': '2017-05-05T10:04:01 -03:00',
      'TrackProgress': 23,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/ET.png',
      'CountryName': 'Ethiopia'
    },
    {
      'Id': 507,
      'Avatar': 'https://randomuser.me/api/portraits/men/35.jpg',
      'Position': 'up',
      'Name': 'Santiago Mccall',
      'AthleteNumber': 38643,
      'BeatsPerMinute': 108,
      'TopSpeed': 4.5,
      'Registered': '2017-11-03T09:33:37 -02:00',
      'TrackProgress': 35,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/FJ.png',
      'CountryName': 'Fiji'
    },
    {
      'Id': 133,
      'Avatar': 'https://randomuser.me/api/portraits/men/24.jpg',
      'Position': 'up',
      'Name': 'Mercado Sykes',
      'AthleteNumber': 37610,
      'BeatsPerMinute': 93,
      'TopSpeed': 5.9,
      'Registered': '2017-06-24T12:21:40 -03:00',
      'TrackProgress': 31,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/FI.png',
      'CountryName': 'Finland'
    },
    {
      'Id': 339,
      'Avatar': 'https://randomuser.me/api/portraits/men/24.jpg',
      'Position': 'up',
      'Name': 'Marva Slater',
      'AthleteNumber': 31094,
      'BeatsPerMinute': 94,
      'TopSpeed': 4.4,
      'Registered': '2017-01-13T05:25:24 -02:00',
      'TrackProgress': 33,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/FR.png',
      'CountryName': 'France'
    },
    {
      'Id': 94,
      'Avatar': 'https://randomuser.me/api/portraits/men/5.jpg',
      'Position': 'down',
      'Name': 'Donna Thomas',
      'AthleteNumber': 20261,
      'BeatsPerMinute': 92,
      'TopSpeed': 5.4,
      'Registered': '2017-09-12T12:32:25 -03:00',
      'TrackProgress': 30,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/GA.png',
      'CountryName': 'Gabon'
    },
    {
      'Id': 85,
      'Avatar': 'https://randomuser.me/api/portraits/men/40.jpg',
      'Position': 'up',
      'Name': 'Paulette Burks',
      'AthleteNumber': 31786,
      'BeatsPerMinute': 101,
      'TopSpeed': 5.8,
      'Registered': '2017-09-12T11:05:30 -03:00',
      'TrackProgress': 46,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/GM.png',
      'CountryName': 'Gambia'
    },
    {
      'Id': 594,
      'Avatar': 'https://randomuser.me/api/portraits/men/42.jpg',
      'Position': 'current',
      'Name': 'Dionne Montoya',
      'AthleteNumber': 25606,
      'BeatsPerMinute': 93,
      'TopSpeed': 5.8,
      'Registered': '2017-01-01T06:43:07 -02:00',
      'TrackProgress': 27,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/GE.png',
      'CountryName': 'Georgia'
    },
    {
      'Id': 65,
      'Avatar': 'https://randomuser.me/api/portraits/men/40.jpg',
      'Position': 'current',
      'Name': 'Hamilton Klein',
      'AthleteNumber': 28765,
      'BeatsPerMinute': 99,
      'TopSpeed': 5.3,
      'Registered': '2017-09-13T03:45:39 -03:00',
      'TrackProgress': 23,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/DE.png',
      'CountryName': 'Germany'
    },
    {
      'Id': 402,
      'Avatar': 'https://randomuser.me/api/portraits/men/40.jpg',
      'Position': 'down',
      'Name': 'Lawson Summers',
      'AthleteNumber': 18424,
      'BeatsPerMinute': 103,
      'TopSpeed': 5.5,
      'Registered': '2017-04-20T07:31:08 -03:00',
      'TrackProgress': 46,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/GH.png',
      'CountryName': 'Ghana'
    },
    {
      'Id': 483,
      'Avatar': 'https://randomuser.me/api/portraits/men/44.jpg',
      'Position': 'down',
      'Name': 'Desiree Rodriquez',
      'AthleteNumber': 22884,
      'BeatsPerMinute': 107,
      'TopSpeed': 4.9,
      'Registered': '2017-04-08T07:42:11 -03:00',
      'TrackProgress': 47,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/GR.png',
      'CountryName': 'Greece'
    },
    {
      'Id': 315,
      'Avatar': 'https://randomuser.me/api/portraits/men/45.jpg',
      'Position': 'down',
      'Name': 'Ivy Walls',
      'AthleteNumber': 30122,
      'BeatsPerMinute': 101,
      'TopSpeed': 4.8,
      'Registered': '2017-10-20T11:53:28 -03:00',
      'TrackProgress': 39,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/GD.png',
      'CountryName': 'Grenada'
    },
    {
      'Id': 188,
      'Avatar': 'https://randomuser.me/api/portraits/men/33.jpg',
      'Position': 'down',
      'Name': 'Jane Gilbert',
      'AthleteNumber': 24642,
      'BeatsPerMinute': 105,
      'TopSpeed': 4.5,
      'Registered': '2017-09-29T12:53:29 -03:00',
      'TrackProgress': 42,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/GT.png',
      'CountryName': 'Guatemala'
    },
    {
      'Id': 521,
      'Avatar': 'https://randomuser.me/api/portraits/men/13.jpg',
      'Position': 'down',
      'Name': 'Kelsey Osborne',
      'AthleteNumber': 33775,
      'BeatsPerMinute': 102,
      'TopSpeed': 5.6,
      'Registered': '2017-01-05T10:40:27 -02:00',
      'TrackProgress': 32,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/GN.png',
      'CountryName': 'Guinea'
    },
    {
      'Id': 15,
      'Avatar': 'https://randomuser.me/api/portraits/men/33.jpg',
      'Position': 'down',
      'Name': 'Jeanie Witt',
      'AthleteNumber': 17994,
      'BeatsPerMinute': 102,
      'TopSpeed': 5.9,
      'Registered': '2017-06-10T05:48:28 -03:00',
      'TrackProgress': 37,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/GW.png',
      'CountryName': 'Guinea-Bissau'
    },
    {
      'Id': 381,
      'Avatar': 'https://randomuser.me/api/portraits/men/29.jpg',
      'Position': 'current',
      'Name': 'Barr Tanner',
      'AthleteNumber': 19155,
      'BeatsPerMinute': 100,
      'TopSpeed': 5.7,
      'Registered': '2017-04-20T04:28:06 -03:00',
      'TrackProgress': 27,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/GY.png',
      'CountryName': 'Guyana'
    },
    {
      'Id': 490,
      'Avatar': 'https://randomuser.me/api/portraits/men/16.jpg',
      'Position': 'current',
      'Name': 'Jewel Cardenas',
      'AthleteNumber': 14226,
      'BeatsPerMinute': 110,
      'TopSpeed': 5.2,
      'Registered': '2017-01-06T03:14:59 -02:00',
      'TrackProgress': 45,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/HT.png',
      'CountryName': 'Haiti'
    },
    {
      'Id': 543,
      'Avatar': 'https://randomuser.me/api/portraits/men/49.jpg',
      'Position': 'down',
      'Name': 'Althea Mullins',
      'AthleteNumber': 20404,
      'BeatsPerMinute': 108,
      'TopSpeed': 4.8,
      'Registered': '2017-07-04T07:58:07 -03:00',
      'TrackProgress': 35,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/VA.png',
      'CountryName': 'Holy See (Vatican City State)'
    },
    {
      'Id': 30,
      'Avatar': 'https://randomuser.me/api/portraits/men/47.jpg',
      'Position': 'current',
      'Name': 'Hays Key',
      'AthleteNumber': 32339,
      'BeatsPerMinute': 100,
      'TopSpeed': 5.5,
      'Registered': '2017-03-11T03:40:46 -02:00',
      'TrackProgress': 35,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/HN.png',
      'CountryName': 'Honduras'
    },
    {
      'Id': 329,
      'Avatar': 'https://randomuser.me/api/portraits/men/13.jpg',
      'Position': 'current',
      'Name': 'Linda Perez',
      'AthleteNumber': 44518,
      'BeatsPerMinute': 105,
      'TopSpeed': 4.2,
      'Registered': '2017-07-05T02:41:53 -03:00',
      'TrackProgress': 32,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/HU.png',
      'CountryName': 'Hungary'
    },
    {
      'Id': 518,
      'Avatar': 'https://randomuser.me/api/portraits/men/7.jpg',
      'Position': 'down',
      'Name': 'Luz Vinson',
      'AthleteNumber': 17767,
      'BeatsPerMinute': 97,
      'TopSpeed': 4.2,
      'Registered': '2017-01-09T10:52:53 -02:00',
      'TrackProgress': 46,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/IS.png',
      'CountryName': 'Iceland'
    },
    {
      'Id': 452,
      'Avatar': 'https://randomuser.me/api/portraits/men/6.jpg',
      'Position': 'down',
      'Name': 'Patrice Patrick',
      'AthleteNumber': 13135,
      'BeatsPerMinute': 102,
      'TopSpeed': 4.9,
      'Registered': '2017-05-10T01:53:17 -03:00',
      'TrackProgress': 36,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/IN.png',
      'CountryName': 'India'
    },
    {
      'Id': 168,
      'Avatar': 'https://randomuser.me/api/portraits/men/49.jpg',
      'Position': 'down',
      'Name': 'Wooten Woodard',
      'AthleteNumber': 27991,
      'BeatsPerMinute': 108,
      'TopSpeed': 5.8,
      'Registered': '2017-09-27T09:10:18 -03:00',
      'TrackProgress': 48,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/ID.png',
      'CountryName': 'Indonesia'
    },
    {
      'Id': 513,
      'Avatar': 'https://randomuser.me/api/portraits/men/22.jpg',
      'Position': 'current',
      'Name': 'Moreno Rutledge',
      'AthleteNumber': 20745,
      'BeatsPerMinute': 103,
      'TopSpeed': 5.9,
      'Registered': '2017-01-08T11:35:48 -02:00',
      'TrackProgress': 46,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/IR.png',
      'CountryName': 'Iran, Islamic Republic Of'
    },
    {
      'Id': 296,
      'Avatar': 'https://randomuser.me/api/portraits/men/2.jpg',
      'Position': 'down',
      'Name': 'Golden Christian',
      'AthleteNumber': 39029,
      'BeatsPerMinute': 92,
      'TopSpeed': 5.2,
      'Registered': '2017-06-19T06:31:54 -03:00',
      'TrackProgress': 48,
      'CountryFlag': 'https://flags.fmcdn.net/data/flags/h20/IQ.png',
      'CountryName': 'Iraq'
    }
  ];

  for (const i of athletesData) {
    i.CountryFlag = i.CountryFlag.toLocaleLowerCase();
  }
