// tslint:disable:object-literal-sort-keys

export const gridsRoutesData = {
    "grid": { displayName: "Grid Basic Features", parentName: "Grid" },
    "grid-summary": { displayName: "Grid Summary", parentName: "Grid" },
    "grid-groupby": { displayName: "Grid GroupBy", parentName: "Grid" },
    "grid-groupby-paging": { displayName: "Grid GroupBy Paging", parentName: "Grid" },
    "grid-groupby-styling": { displayName: "Grid GroupBy Styling", parentName: "Grid" },
    "grid-groupby-summary": { displayName: "Grid GroupBy Summary", parentName: "Grid" },
    "grid-groupby-summary-styling": { displayName: "Grid GroupBy Summary Styling", parentName: "Grid" },
    "grid-editing": { displayName: "Grid Editing", parentName: "Grid" },
    "grid-editing-events": { displayName: "Grid Editing Events", parentName: "Grid" },
    "grid-editing-style": { displayName: "Grid Editing Style", parentName: "Grid" },
    "grid-row-editing": { displayName: "Grid Row Editing", parentName: "Grid" },
    "grid-row-drag": { displayName: "Grid Row Drag", parentName: "Grid" },
    "grid-row-drag-base": { displayName: "Grid Row Drag - Base", parentName: "Grid" },
    "grid-row-drag-to-grid": { displayName: "Row Drag between Grids", parentName: "Grid" },
    "grid-row-reorder": { displayName: "Grid Row Reorder", parentName: "Grid" },
    "grid-batch-editing": { displayName: "Grid Batch Editing", parentName: "Grid" },
    "grid-displayDensity": { displayName: "Grid Display Density", parentName: "Grid" },
    "grid-cell-styling": { displayName: "Grid Conditional Cell Styling", parentName: "Grid" },
    "grid-filtering-sample": { displayName: "Grid Filtering", parentName: "Grid" },
    "grid-filtering-template-sample": { displayName: "Grid Filtering Template", parentName: "Grid" },
    "grid-excel-style-filtering-sample-1": { displayName: "Grid Excel Style Filtering", parentName: "Grid" },
    "grid-excel-style-filtering-sample-2": { displayName: "Grid Excel Style Filtering Operations", parentName: "Grid" },
    "grid-excel-style-filtering-sample-3": { displayName: "Grid Excel Style Filtering Templates", parentName: "Grid" },
    "grid-excel-style-filtering-style": { displayName: "Grid Excel Style Filtering Styling", parentName: "Grid" },
    "grid-filter-conditions": { displayName: "Custom Filtering Conditions", parentName: "Grid" },
    "grid-pager-sample": { displayName: "Grid Pager", parentName: "Grid" },
    "grid-paging-sample": { displayName: "Grid Paging", parentName: "Grid" },
    "grid-pinning-styling": { displayName: "Grid Pinning Styling", parentName: "Grid" },
    "grid-resizing-sample": { displayName: "Grid Resizing", parentName: "Grid" },
    "grid-resize-line-styling-sample": { displayName: "Grid Resize Line Styling", parentName: "Grid" },
    "grid-sample-2": { displayName: "Grid Financial Sample", parentName: "Grid" },
    "grid-sample-pinning": { displayName: "Grid Header Template with Pinning", parentName: "Grid" },
    "grid-sample-toolbar-pinning": { displayName: "Grid Toolbar Pinning", parentName: "Grid" },
    "grid-sample-4": { displayName: "Grid Remote Virtualization", parentName: "Grid" },
    "grid-remote-filtering": { displayName: "Grid Remote Filtering", parentName: "Grid" },
    "grid-selection": { displayName: "Grid Selection", parentName: "Grid" },
    "grid-selection-template-numbering": { displayName: "Grid Row Selectors Template - Numbers", parentName: "Grid" },
    "grid-selection-template-excel": { displayName: "Grid Row Selectors Template - Excel", parentName: "Grid" },
    "grid-search-sample": { displayName: "Grid Search", parentName: "Grid" },
    "grid-column-hiding-sample": { displayName: "Grid Column Hiding", parentName: "Grid" },
    "grid-column-hiding-toolbar-sample": { displayName: "Grid Column Hiding with Toolbar", parentName: "Grid" },
    "grid-sorting-sample": { displayName: "Grid Sorting", parentName: "Grid" },
    "grid-sorting-styling": { displayName: "Grid Sorting Styling", parentName: "Grid" },
    "grid-toolbar-sample-1": { displayName: "Grid Toolbar Title", parentName: "Grid" },
    "grid-toolbar-sample-2": { displayName: "Grid Toolbar Options", parentName: "Grid" },
    "grid-toolbar-sample-3": { displayName: "Grid Toolbar Export", parentName: "Grid" },
    "grid-toolbar-sample-4": { displayName: "Grid Toolbar Custom Content", parentName: "Grid" },
    "grid-moving-sample": { displayName: "Grid Column Moving", parentName: "Grid" },
    "grid-moving-styled-sample": { displayName: "Grid Column Moving Styled", parentName: "Grid" },
    "multi-column-headers": { displayName: "Grid Multi Column Headers", parentName: "Grid" },
    "multi-column-header-template": { displayName: "Grid Multi Column Header Template", parentName: "Grid" },
    "multi-column-headers-styling": { displayName: "Grid Multi Column Headers Styling", parentName: "Grid" },
    "grid-remote-paging-sample": { displayName: "Grid Remote Paging", parentName: "Grid" },
    "grid-paste": { displayName: "Grid Paste From Excel", parentName: "Grid" },
    "grid-custom-keyboard-navigation": { displayName: "Custom Keyboard Navigation", parentName: "Grid" },
    "grid-state": { displayName: "Grid Save and Load State", parentName: "Grid" },
    "grid-about": { displayName: "Grid About", parentName: "Grid" },
    "grid-multi-cell-selection": { displayName: "Grid Multi cell selection", parentName: "Grid" },
    "grid-multi-cell-selection-style": { displayName: "Grid Multi Cell Selection Style", parentName: "Grid" },
    "grid-selection-custom-summaries": { displayName: "Grid Selection Based Summaries", parentName: "Grid" },
    "grid-multi-row-layout": { displayName: "Grid Multi Row Layout", parentName: "Grid" },
    "grid-multi-row-layout-configuration": { displayName: "Grid Multi Row Layout Configuration", parentName: "Grid" },
    "grid-multi-row-layout-styling": { displayName: "Grid Multi Row Layout Styling", parentName: "Grid" },
    "grid-mrl-custom-navigation":
        { displayName: "Grid Multi Row Layout Custom Keyboard Navigation", parentName: "Grid" },
    "custom-grid-paging-style": { displayName: "Custom Grid Paging Style", parentName: "Grid" },
    "grid-nested-data-binding": { displayName: "Grid Nested Data Binding", parentName: "Grid" },
    "grid-composite-data-binding": { displayName: "Grid Composite Data Binding", parentName: "Grid" },
    "grid-row-edit-style": { displayName: "Grid Row Edit Style", parentName: "Grid" },
    "grid-contextmenu-sample": { displayName: "Grid Context Menu", parentName: "Grid" },
    "grid-column-hiding-style": { displayName: "Grid Column Hiding Style", parentName: "Grid" },
    "grid-clipboard-operations-sample": { displayName: "Grid Clipboard Operations", parentName: "Grid" },
    "grid-toolbar-style": { displayName: "Grid Toolbar Style", parentName: "Grid" },
    "grid-filtering-style": { displayName: "Grid Filtering Style", parentName: "Grid" },
    "grid-cell-selection": { displayName: "Grid Cell Selection", parentName: "Grid" },
    "grid-advanced-filtering": { displayName: "Grid Advanced Filtering", parentName: "Grid" },
    "grid-advanced-filtering-style": { displayName: "Grid Advanced Filtering Style", parentName: "Grid" },
    "grid-excel-style-filtering-load-on-demand":
        { displayName: "Grid Excel Style Filtering Load On Demand", parentName: "Grid" },
    "grid-conditional-row-selectors": { displayName: "Grid Conditional Row Selectors", parentName: "Grid" },
    "grid-dynamic-chart-data": { displayName: "Grid Dynamic Chart Data", parentName: "Grid" }
};
