// tslint:disable:object-literal-sort-keys

export const gridsRoutesData = {
    "grid": { displayName: "Grid Basic Features", parentName: "Grid" },
    "grid-summary": { displayName: "Grid Summary", parentName: "Grid" },
    "grid-groupby": { displayName: "Grid GroupBy", parentName: "Grid" },
    "grid-groupby-summary": { displayName: "Grid GroupBy Summary", parentName: "Grid" },
    "grid-editing": { displayName: "Grid Editing", parentName: "Grid" },
    "grid-row-editing": { displayName: "Grid Row Editing", parentName: "Grid" },
    "grid-row-drag": { displayName: "Grid Row Drag", parentName: "Grid" },
    "grid-row-drag-base": { displayName: "Grid Row Drag - Base", parentName: "Grid" },
    "grid-row-drag-to-grid": { displayName: "Row Drag between Grids", parentName: "Grid" },
    "grid-row-reorder": { displayName: "Grid Row Reorder", parentName: "Grid" },
    "grid-batch-editing": { displayName: "Grid Batch Editing", parentName: "Grid" },
    "grid-displayDensity": { displayName: "Grid Display Density", parentName: "Grid" },
    "grid-cell-styling": { displayName: "Grid Conditional Cell Styling", parentName: "Grid" },
    "grid-filtering-sample": { displayName: "Grid Filtering", parentName: "Grid" },
    "grid-filtering-template-sample": { displayName: "Grid Filtering Template", parentName: "Grid" },
    "grid-excel-style-filtering-sample-1": { displayName: "Grid Excel Style Filtering", parentName: "Grid" },
    "grid-excel-style-filtering-sample-2": { displayName: "Grid Excel Style Filtering Operations", parentName: "Grid" },
    "grid-excel-style-filtering-sample-3": { displayName: "Grid Excel Style Filtering Templates", parentName: "Grid" },
    "grid-filter-conditions": { displayName: "Custom Filtering Conditions", parentName: "Grid" },
    "grid-paging-sample": { displayName: "Grid Paging", parentName: "Grid" },
    "grid-resizing-sample": { displayName: "Grid Resizing", parentName: "Grid" },
    "grid-resize-line-styling-sample": { displayName: "Grid Resize Line Styling", parentName: "Grid" },
    "grid-sample-2": { displayName: "Grid Financial Sample", parentName: "Grid" },
    "grid-sample-pinning": { displayName: "Grid Pinning", parentName: "Grid" },
    "grid-sample-4": { displayName: "Grid Remote Virtualization", parentName: "Grid" },
    "grid-remote-filtering": { displayName: "Grid Remote Filtering", parentName: "Grid" },
    "grid-selection": { displayName: "Grid Selection", parentName: "Grid" },
    "grid-search-sample": { displayName: "Grid Search", parentName: "Grid" },
    "grid-column-hiding-sample": { displayName: "Grid Column Hiding", parentName: "Grid" },
    "grid-column-hiding-toolbar-sample": { displayName: "Grid Column Hiding with Toolbar", parentName: "Grid" },
    "grid-sorting-sample": { displayName: "Grid Sorting", parentName: "Grid" },
    "grid-toolbar-sample-1": { displayName: "Grid Toolbar Title", parentName: "Grid" },
    "grid-toolbar-sample-2": { displayName: "Grid Toolbar Options", parentName: "Grid" },
    "grid-toolbar-sample-3": { displayName: "Grid Toolbar Export", parentName: "Grid" },
    "grid-toolbar-sample-4": { displayName: "Grid Toolbar Custom Content", parentName: "Grid" },
    "grid-moving-sample": { displayName: "Grid Column Moving", parentName: "Grid" },
    "grid-moving-styled-sample": { displayName: "Grid Column Moving Styled", parentName: "Grid" },
    "multi-column-headers": { displayName: "Grid Multi Column Headers", parentName: "Grid" },
    "grid-remote-paging-sample": { displayName: "Grid Remote Paging", parentName: "Grid" },
    "grid-paste": { displayName: "Grid Paste From Excel", parentName: "Grid" },
    "grid-custom-keyboard-navigation": { displayName: "Custom Keyboard Navigation", parentName: "Grid" },
    "grid-state": { displayName: "Grid Save and Load State", parentName: "Grid" },
    "grid-about": { displayName: "Grid About", parentName: "Grid" },
    "grid-multi-cell-selection": { displayName: "Grid Multi cell selection", parentName: "Grid" },
    "grid-multi-row-layout": { displayName: "Grid Multi Row Layout", parentName: "Grid" },
    "grid-multi-row-layout-configuration": { displayName: "Grid Multi Row Layout Configuration", parentName: "Grid" },
    "grid-mrl-custom-navigation":
        { displayName: "Grid Multi Row Layout Custom Keyboard Navigation", parentName: "Grid" },
    "custom-grid-paging-style": { displayName: "Custom Grid Paging Style", parentName: "Grid" },
    "grid-nested-data-binding": { displayName: "Grid Nested Data Binding", parentName: "Grid" },
    "grid-composite-data-binding": { displayName: "Grid Composite Data Binding", parentName: "Grid" },
    "grid-contextmenu-sample": { displayName: "Grid Context Menu", parentName: "Grid" }
};
