export const schedulingRoutesData = {
    'calendar-sample-1': { displayName: 'Calendar Multi Selection Mode', parentName: 'Calendar' },
    'calendar-sample-2': { displayName: 'Customized Dates Display', parentName: 'Calendar' },
    'calendar-sample-3': { displayName: 'Calendar Range Mode', parentName: 'Calendar' },
    'calendar-sample-4': { displayName: 'Conditional Templating and Date Parsing ', parentName: 'Calendar' },
    'calendar-sample-5': { displayName: 'Calendar Selection Mode', parentName: 'Calendar' },
    'calendar-sample-6': { displayName: 'Calendar Disabled Dates', parentName: 'Calendar' },
    'calendar-sample-7': { displayName: 'Calendar Special Dates', parentName: 'Calendar' },
    'calendar-sample-8': { displayName: 'Calendar Range Mode', parentName: 'Calendar' },
    'calendar-rtl-sample': { displayName: 'Calendar RTL Support', parentName: 'Calendar' },
    'calendar-days-view': { displayName: 'Calendar Days View', parentName: 'Calendar' },
    'calendar-months-view': { displayName: 'Calendar Months View', parentName: 'Calendar' },
    'calendar-years-view': { displayName: 'Calendar Years View', parentName: 'Calendar' },
    'multiview-calendar': {displayName: 'Multiview Calendar', parentName: 'Calendar'},
    'calendar-styling-sample': { displayName: 'Calendar Styling', parentName: 'Calendar' },
    'datepicker-dropdown': { displayName: 'Editable Datepicker', parentName: 'Datepicker' },
    'datepicker-sample-1': { displayName: 'Simple Datepicker', parentName: 'Datepicker' },
    'datepicker-sample-2': { displayName: 'One-way data bound Datepicker', parentName: 'Datepicker' },
    'datepicker-sample-3': { displayName: 'Datepicker Buttons', parentName: 'Datepicker' },
    'datepicker-sample-4': { displayName: 'Datepicker Formatter', parentName: 'Datepicker' },
    'datepicker-sample-5': { displayName: 'Datepicker Locales', parentName: 'Datepicker' },
    'datepicker-sample-6': { displayName: 'Datepicker Input Group Template', parentName: 'Datepicker' },
    'datepicker-sample-7': { displayName: 'Dropdown Datepicker Template', parentName: 'Datepicker' },
    'datepicker-sample-8': { displayName: 'Custom Action Buttons', parentName: 'Datepicker' },
    'datepicker-sample-9': { displayName: 'Range Datepicker', parentName: 'Datepicker' },
    'datepicker-styling-sample': { displayName: 'Datepicker Styling', parentName: 'Datepicker' },
    'template-driven-form': { displayName: 'Date & Time Picker Template Driven Form', parentName: 'Datepicker' },
    'reactive-form': { displayName: 'Date & Time Picker Reactive Form', parentName: 'Reactive Forms' },
    'datetime-basic': { displayName: 'Date Time Basic', parentName: 'Date Time Editor' },
    'datetime-advanced': { displayName: 'Date Time Advanced', parentName: 'Date Time Editor' },
    'monthpicker-sample-1': { displayName: 'Default Month Picker', parentName: 'Monthpicker' },
    'monthpicker-sample-3': { displayName: 'Localized Month Picker', parentName: 'Monthpicker' },
    'monthpicker-styling': { displayName: 'Styled Month Picker', parentName: 'Monthpicker' },
    'timepicker-dropdown': { displayName: 'Timepicker Overview', parentName: 'Timepicker' },
    'timepicker-sample-1': { displayName: 'Timepicker Dialog', parentName: 'Timepicker' },
    'timepicker-sample-4': { displayName: 'Timepicker Validation', parentName: 'Timepicker' },
    'timepicker-sample-5': { displayName: 'Timepicker Templating', parentName: 'Timepicker' },
    'timepicker-sample-6': { displayName: 'Timepicker Action Buttons Template', parentName: 'Timepicker' },
    'timepicker-styling': { displayName: 'Styled Timepicker', parentName: 'Timepicker' },
    'basic-daterangepicker': { displayName: 'Single Read-Only Input', parentName: 'Date Range Picker' },
    'daterangepicker-start-end': { displayName: 'Separate Editable Inputs', parentName: 'Date Range Picker' },
    'daterangepicker-mode': { displayName: 'Dropdown Mode', parentName: 'Date Range Picker' },
    'daterangepicker-validation': { displayName: 'Validation', parentName: 'Date Range Picker' },
    'styled-daterangepicker': { displayName: 'Styling', parentName: 'Date Range Picker' },
    'flight-booking': { displayName: 'Flight Booking', parentName: 'Date Range Picker' }
};
