export const schedulingRoutesData = {
    "calendar-sample-1": { displayName: "Calendar Overview", parentName: "Calendar" },
    "calendar-sample-2": { displayName: "Customized Dates Display", parentName: "Calendar" },
    "calendar-sample-3": { displayName: "Calendar with Date Range", parentName: "Calendar" },
    "calendar-sample-4": { displayName: "Conditional Templating and Date Parsing ", parentName: "Calendar" },
    "calendar-sample-5": { displayName: "Calendar Selection", parentName: "Calendar" },
    "calendar-sample-6": { displayName: "Calendar disabled dates", parentName: "Calendar" },
    "calendar-sample-7": { displayName: "Calendar special dates", parentName: "Calendar" },
    "calendar-styling-sample": { displayName: "Calendar Styling", parentName: "Calendar" },
    "calendar-views": { displayName: "Calendar Views", parentName: "Calendar" },
    "datepicker-dropdown": { displayName: "Editable Datepicker", parentName: "Datepicker" },
    "datepicker-sample-1": { displayName: "Simple Datepicker", parentName: "Datepicker" },
    "datepicker-sample-2": { displayName: "One-way data bound Datepicker", parentName: "Datepicker" },
    "datepicker-sample-3": { displayName: "Datepicker Buttons", parentName: "Datepicker" },
    "datepicker-sample-4": { displayName: "Datepicker Formatter", parentName: "Datepicker" },
    "datepicker-sample-5": { displayName: "Datepicker Locales", parentName: "Datepicker" },
    "datepicker-sample-6": { displayName: "Datepicker Input Group Template", parentName: "Datepicker" },
    "datepicker-sample-7": { displayName: "Dropdown Datepicker Template", parentName: "Datepicker" },
    "datepicker-sample-8": { displayName: "Custom Action Buttons", parentName: "Datepicker" },
    "datepicker-sample-9": { displayName: "Range Datepicker", parentName: "Datepicker" },
    "datetimeeditor-sample-1": {displayName: "Date Time Editor Sample", parentName: "Date Time Editor"},
    // "datetimeditor-sample-2": {displayName: "Date Time Editor Sample", parentName: "Datetimeeditor"},
    "monthpicker-sample-1": { displayName: "Default Month Picker", parentName: "Monthpicker" },
    "monthpicker-sample-2": { displayName: "Month Picker with Format Options", parentName: "Monthpicker" },
    "monthpicker-sample-3": { displayName: "Localized Month Picker", parentName: "Monthpicker" },
    "timepicker-dropdown": { displayName: "Timepicker DropDown", parentName: "Timepicker" },
    "timepicker-sample-1": { displayName: "Timepicker Overview", parentName: "Timepicker" },
    "timepicker-sample-2": { displayName: "One-way data bound Timepicker", parentName: "Timepicker" },
    "timepicker-sample-3": { displayName: "Timepicker Delta and Spin Mode", parentName: "Timepicker" },
    "timepicker-sample-4": { displayName: "Timepicker Validation", parentName: "Timepicker" },
    "timepicker-sample-5": { displayName: "Timepicker Input Group Template", parentName: "Timepicker" },
    "timepicker-sample-6": { displayName: "Timepicker Input Group Template Dropdown", parentName: "Timepicker" },
    "timepicker-sample-7": { displayName: "Custom Action Buttons", parentName: "Timepicker" },
    "timepicker-sample-8": { displayName: "Timepicker Format", parentName: "Timepicker" },
    "multiview-calendar": {displayName: "Multiview Calendar", parentName: "Calendar"}
};
