// tslint:disable:object-literal-sort-keys
// tslint:disable:max-line-length

export const chartsRoutesData = {
    "doughnut-chart-explosion": { displayName: "Doughnut Chart Explosion", parentName: "Doughnut Chart" },
    "doughnut-chart-overview": { displayName: "Doughnut Chart Overview", parentName: "Doughnut Chart" },
    "doughnut-chart-selection": { displayName: "Doughnut Chart Selection", parentName: "Doughnut Chart" },
    "pie-chart-data-sample": { displayName: "Pie Chart Data Sample", parentName: "Pie Chart" },
    "pie-chart-explosion": { displayName: "Pie Chart Explosion", parentName: "Pie Chart" },
    "pie-chart-legend": { displayName: "Pie Chart Legend", parentName: "Pie Chart" },
    "pie-chart-others": { displayName: "Pie Chart Others Slice", parentName: "Pie Chart" },
    "pie-chart-selection": { displayName: "Pie Chart Selection", parentName: "Pie Chart" },
    "category-chart-overview-sample": { displayName: "Category Chart Overview", parentName: "Category Chart" },
    "category-chart-annotations": { displayName: "Category Chart Annotations", parentName: "Category Chart" },
    "category-chart-overlap-columns": { displayName: "Category Chart Overlap Columns", parentName: "Category Chart" },
    "category-chart-highlighting-sample": { displayName: "Category Chart Highlighting", parentName: "Category Chart" },
    "category-chart-high-volume-sample": { displayName: "Category Chart High Volume", parentName: "Category Chart" },
    "financial-chart-overview-sample": { displayName: "Financial Chart Overview", parentName: "Financial Chart" },
    "category-chart-high-frequency-sample": { displayName: "Category Chart High Frequency", parentName: "Category Chart" },
    "category-chart-axis-options-sample": { displayName: "Category Chart Axis Options", parentName: "Category Chart" },
    "category-chart-config-options-sample": { displayName: "Category Chart Configuring Options", parentName: "Category Chart" },
    "category-chart-tooltip-template": { displayName: "Category Chart Tooltips Template", parentName: "Category Chart" },
    "category-chart-tooltip-types": { displayName: "Category Chart Tooltip Types", parentName: "Category Chart" },
    "category-chart-trendline": { displayName: "Category Chart Trendline", parentName: "Category Chart" },
    "financial-chart-performance": { displayName: "Financial Chart Performance", parentName: "Financial Chart" },
    "financial-chart-annotations": { displayName: "Financial Chart Annotations", parentName: "Financial Chart" },
    "financial-chart-titles": { displayName: "Financial Chart Titles", parentName: "Financial Chart" },
    "financial-chart-panes": { displayName: "Financial Chart Panes", parentName: "Financial Chart" },
    "financial-chart-multiple-data": { displayName: "Financial Chart Multiple Sources", parentName: "Financial Chart" },
    "financial-chart-multiple-feeds": { displayName: "Financial Chart Multiple Feeds", parentName: "Financial Chart" },
    "financial-chart-indicator-types": { displayName: "Financial Chart Indicator Types", parentName: "Financial Chart" },
    "financial-chart-volume-type": { displayName: "Financial Chart Volume Types", parentName: "Financial Chart" },
    "financial-chart-custom-indicators": { displayName: "Financial Chart Custom Indicators", parentName: "Financial Chart" },
    "financial-chart-high-volume": { displayName: "Financial Chart High Volume", parentName: "Financial Chart" },
    "financial-chart-high-frequency": { displayName: "Financial Chart High Frequency", parentName: "Financial Chart" },
    "financial-chart-axis-types": { displayName: "Financial Chart Axis Types", parentName: "Financial Chart" },
    "financial-chart-tooltip-template": { displayName: "Financial Chart Tooltips Template", parentName: "Financial Chart" },
    "financial-chart-tooltip-types": { displayName: "Financial Chart Tooltip Types", parentName: "Financial Chart" },
    "financial-chart-time-based-data": { displayName: "Financial Chart Time Based Data", parentName: "Financial Chart" },
    "financial-chart-trendlines": { displayName: "Financial Chart Trendlines", parentName: "Financial Chart" }
};
