/* tslint:disable */

export const chartsRoutesData = {
    // doughnut-chart
    "doughnut-chart-explosion": { displayName: "Doughnut Chart Explosion", parentName: "Doughnut Chart" },
    "doughnut-chart-overview": { displayName: "Doughnut Chart Overview", parentName: "Doughnut Chart" },
    "doughnut-chart-selection": { displayName: "Doughnut Chart Selection", parentName: "Doughnut Chart" },
    "doughnut-chart-legend": { displayName: "Doughnut Chart Legend", parentName: "Doughnut Chart" },
    "doughnut-chart-rings": { displayName: "Doughnut Chart Rings", parentName: "Doughnut Chart" },
    // pie-chart
    "pie-chart-overview": { displayName: "Pie Chart Overview", parentName: "Pie Chart" },
    "pie-chart-explosion": { displayName: "Pie Chart Explosion", parentName: "Pie Chart" },
    "pie-chart-legend": { displayName: "Pie Chart Legend", parentName: "Pie Chart" },
    "pie-chart-others": { displayName: "Pie Chart Others Slice", parentName: "Pie Chart" },
    "pie-chart-selection": { displayName: "Pie Chart Selection", parentName: "Pie Chart" },
    // category-chart
    "category-chart-overview": { displayName: "Category Chart Overview", parentName: "Category Chart" },
    "category-chart-annotations": { displayName: "Category Chart Annotations", parentName: "Category Chart" },
    "category-chart-overlap-columns": { displayName: "Category Chart Overlap Columns", parentName: "Category Chart" },
    "category-chart-highlighting-sample": { displayName: "Category Chart Highlighting", parentName: "Category Chart" },
    "category-chart-high-volume-sample": { displayName: "Category Chart High Volume", parentName: "Category Chart" },
    "category-chart-high-frequency-sample": { displayName: "Category Chart High Frequency", parentName: "Category Chart" },
    "category-chart-axis-options-sample": { displayName: "Category Chart Axis Options", parentName: "Category Chart" },
    "category-chart-config-options-sample": { displayName: "Category Chart Configuring Options", parentName: "Category Chart" },
    "category-chart-tooltip-template": { displayName: "Category Chart Tooltips Template", parentName: "Category Chart" },
    "category-chart-tooltip-types": { displayName: "Category Chart Tooltip Types", parentName: "Category Chart" },
    "category-chart-trendline": { displayName: "Category Chart Trendline", parentName: "Category Chart" },
    // financial-chart
    "financial-chart-overview": { displayName: "Financial Chart Overview", parentName: "Financial Chart" },
    "financial-chart-performance": { displayName: "Financial Chart Performance", parentName: "Financial Chart" },
    "financial-chart-annotations": { displayName: "Financial Chart Annotations", parentName: "Financial Chart" },
    "financial-chart-titles": { displayName: "Financial Chart Titles", parentName: "Financial Chart" },
    "financial-chart-panes": { displayName: "Financial Chart Panes", parentName: "Financial Chart" },
    "financial-chart-multiple-data": { displayName: "Financial Chart Multiple Sources", parentName: "Financial Chart" },
    "financial-chart-multiple-feeds": { displayName: "Financial Chart Multiple Feeds", parentName: "Financial Chart" },
    "financial-chart-indicator-types": { displayName: "Financial Chart Indicator Types", parentName: "Financial Chart" },
    "financial-chart-volume-type": { displayName: "Financial Chart Volume Types", parentName: "Financial Chart" },
    "financial-chart-custom-indicators": { displayName: "Financial Chart Custom Indicators", parentName: "Financial Chart" },
    "financial-chart-high-volume": { displayName: "Financial Chart High Volume", parentName: "Financial Chart" },
    "financial-chart-high-frequency": { displayName: "Financial Chart High Frequency", parentName: "Financial Chart" },
    "financial-chart-axis-types": { displayName: "Financial Chart Axis Types", parentName: "Financial Chart" },
    "financial-chart-tooltip-template": { displayName: "Financial Chart Tooltips Template", parentName: "Financial Chart" },
    "financial-chart-tooltip-types": { displayName: "Financial Chart Tooltip Types", parentName: "Financial Chart" },
    "financial-chart-time-based-data": { displayName: "Financial Chart Time Based Data", parentName: "Financial Chart" },
    "financial-chart-trendlines": { displayName: "Financial Chart Trendlines", parentName: "Financial Chart" },
    // data-chart
    // TODO uncomment when implemented
    // "data-chart-axis-locations": { displayName: "Data Chart Axis Locations", parentName: "Data Chart" },
    "data-chart-axis-annotations": { displayName: "Data Chart Axis Annotations", parentName: "Data Chart" },
    "data-chart-axis-settings": { displayName: "Data Chart Axis Settings", parentName: "Data Chart" },
    "data-chart-axis-sharing": { displayName: "Data Chart Axis Sharing", parentName: "Data Chart" },
    "data-chart-axis-types": { displayName: "Data Chart Axis Types", parentName: "Data Chart" },
    "data-chart-legends": { displayName: "Data Chart Legends", parentName: "Data Chart" },
    "data-chart-navigation": { displayName: "Data Chart Navigation", parentName: "Data Chart" },
    "data-chart-overview": { displayName: "Data Chart Overview", parentName: "Data Chart" },
    // TODO uncomment when implemented
    // "data-chart-performance": { displayName: "Data Chart Performance", parentName: "Data Chart" },
    // "data-chart-series-animations": { displayName: "Data Chart Series Animations", parentName: "Data Chart" },
    "data-chart-series-annotations": { displayName: "Data Chart Series Annotations", parentName: "Data Chart" },
    "data-chart-series-highlighting": { displayName: "Data Chart Series Highlighting", parentName: "Data Chart" },
    "data-chart-series-markers": { displayName: "Data Chart Series Markers", parentName: "Data Chart" },
    "data-chart-series-tooltips": { displayName: "Data Chart Series Tooltips", parentName: "Data Chart" },
    "data-chart-series-trendlines": { displayName: "Data Chart Series Trendlines", parentName: "Data Chart" },
    "data-chart-type-category-series": { displayName: "Data Chart Category Series", parentName: "Data Chart" },
    "data-chart-type-category-area-series": { displayName: "Data Chart Category Area Series", parentName: "Data Chart" },
    "data-chart-type-category-bar-series": { displayName: "Data Chart Category Bar Series", parentName: "Data Chart" },
    "data-chart-type-category-column-series": { displayName: "Data Chart Category Column Series", parentName: "Data Chart" },
    "data-chart-type-category-line-series": { displayName: "Data Chart Category Line Series", parentName: "Data Chart" },
    "data-chart-type-category-point-series": { displayName: "Data Chart Category Point Series", parentName: "Data Chart" },
    "data-chart-type-category-spline-area-series": { displayName: "Data Chart Category Spline Area Series", parentName: "Data Chart" },
    "data-chart-type-category-spline-series": { displayName: "Data Chart Category Spline Series", parentName: "Data Chart" },
    "data-chart-type-category-step-area-series": { displayName: "Data Chart Category Step Area Series", parentName: "Data Chart" },
    "data-chart-type-category-step-line-series": { displayName: "Data Chart Category Step Line Series", parentName: "Data Chart" },
    "data-chart-type-category-waterfall-series": { displayName: "Data Chart Category Waterfall Series", parentName: "Data Chart" },
    "data-chart-type-financial-series": { displayName: "Data Chart Financial Series", parentName: "Data Chart" },
    "data-chart-type-financial-candlestick-series": { displayName: "Data Chart Financial Candlestick Series", parentName: "Data Chart" },
    "data-chart-type-financial-ohlc-series": { displayName: "Data Chart Financial OHLC Series", parentName: "Data Chart" },
    "data-chart-type-polar-series": { displayName: "Data Chart Polar Series", parentName: "Data Chart" },
    "data-chart-type-polar-area-series": { displayName: "Data Chart Polar Area Series", parentName: "Data Chart" },
    "data-chart-type-polar-line-series": { displayName: "Data Chart Polar Line Series", parentName: "Data Chart" },
    "data-chart-type-polar-scatter-series": { displayName: "Data Chart Polar Scatter Series", parentName: "Data Chart" },
    "data-chart-type-polar-spline-area-series": { displayName: "Data Chart Polar Spline Area Series", parentName: "Data Chart" },
    "data-chart-type-polar-spline-series": { displayName: "Data Chart Polar Spline Series", parentName: "Data Chart" },
    "data-chart-type-radial-series": { displayName: "Data Chart Radial Series", parentName: "Data Chart" },
    "data-chart-type-radial-area-series": { displayName: "Data Chart Radial Area Series", parentName: "Data Chart" },
    "data-chart-type-radial-column-series": { displayName: "Data Chart Radial Column Series", parentName: "Data Chart" },
    "data-chart-type-radial-line-series": { displayName: "Data Chart Radial Line Series", parentName: "Data Chart" },
    "data-chart-type-radial-pie-series": { displayName: "Data Chart Radial Pie Series", parentName: "Data Chart" },
    "data-chart-type-range-series": { displayName: "Data Chart Range Series", parentName: "Data Chart" },
    "data-chart-type-range-area-series": { displayName: "Data Chart Range Area Series", parentName: "Data Chart" },
    "data-chart-type-range-column-series": { displayName: "Data Chart Range Column Series", parentName: "Data Chart" },
    "data-chart-type-area-series": { displayName: "Data Chart Scatter Area Series", parentName: "Data Chart" },
    "data-chart-type-contour-series": { displayName: "Data Chart Scatter Contour Series", parentName: "Data Chart" },
    // "data-chart-type-scatter-density-series": { displayName: "Data Chart Scatter Density Series", parentName: "Data Chart" },
    "data-chart-type-scatter-series": { displayName: "Data Chart Scatter Series", parentName: "Data Chart" },
    "data-chart-type-shape-series": { displayName: "Data Chart Scatter Shape Series", parentName: "Data Chart" },
    "data-chart-type-stacked-series": { displayName: "Data Chart Stacked Series", parentName: "Data Chart" },
    "data-chart-type-stacked-100-area-series": { displayName: "Data Chart Stacked 100 Area Series", parentName: "Data Chart" },
    "data-chart-type-stacked-100-bar-series": { displayName: "Data Chart Stacked 100 Bar Series", parentName: "Data Chart" },
    "data-chart-type-stacked-100-column-series": { displayName: "Data Chart Stacked 100 Column Series", parentName: "Data Chart" },
    "data-chart-type-stacked-100-line-series": { displayName: "Data Chart Stacked 100 Line Series", parentName: "Data Chart" },
    "data-chart-type-stacked-100-spline-series": { displayName: "Data Chart Stacked 100 Spline Series", parentName: "Data Chart" },
    "data-chart-type-stacked-area-series": { displayName: "Data Chart Stacked Area Series", parentName: "Data Chart" },
    "data-chart-type-stacked-bar-series": { displayName: "Data Chart Stacked Bar Series", parentName: "Data Chart" },
    "data-chart-type-stacked-column-series": { displayName: "Data Chart Stacked Column Series", parentName: "Data Chart" },
    "data-chart-type-stacked-line-series": { displayName: "Data Chart Stacked Line Series", parentName: "Data Chart" },
    "data-chart-type-stacked-spline-series": { displayName: "Data Chart Stacked Spline Series", parentName: "Data Chart" },

    "data-chart-synchronization": { displayName: "Data Chart Synchronization", parentName: "Data Chart" },
    "data-chart-titles": { displayName: "Data Chart Titles", parentName: "Data Chart" },
    "data-chart-value-overlay": { displayName: "Data Chart Value Overlay", parentName: "Data Chart" },
    // sparkline-chart
    "sparkline-display-types": { displayName: "Sparkline Display Types", parentName: "Sparkline"},
    "sparkline-grid": { displayName: "Sparkline Grid", parentName: "Sparkline"},
    "sparkline-markers": { displayName: "Sparkline Markers", parentName: "Sparkline"},
    "sparkline-normal-range": { displayName: "Sparkline Normal Range", parentName: "Sparkline"},
    "sparkline-trendlines": { displayName: "Sparkline Trendlines", parentName: "Sparkline"},
    "sparkline-unknown-values": { displayName: "Sparkline Unknown Values", parentName: "Sparkline"},
    // zoomslider-chart
    "zoomslider-overview": { displayName: "Zoom Slider Overview", parentName: "Zoom Slider"}
};
