/* eslint-disable max-len */

export const hierarchicalGridRoutesData = {
    'hierarchical-grid-editing': { displayName: 'Hierarchical Grid Editing', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-editing-events': { displayName: 'Hierarchical Grid Editing Events', parentName: 'Hierarchical Grid'},
    'hierarchical-grid-editing-style': { displayName: 'Hierarchical Grid Editing Style', parentName: 'Hierarchical Grid'},
    'hierarchical-grid-row-editing': { displayName: 'Hierarchical Grid Row Editing', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-row-drag': { displayName: 'Hierarchical Grid Row Drag', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-multi-row-drag': { displayName: 'Hierarchical Grid Multi Row Drag', parentName: 'Hierarchical Grid' },
    'hierarchical-row-drag-base': { displayName: 'Hierarchical Grid Row Drag - Base', parentName: 'Hierarchical Grid' },
    'hierarchical-row-reorder': { displayName: 'Hierarchical Grid Row Reorder', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-batch-editing': { displayName: 'Hierarchical Grid Batch Editing', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-filtering': { displayName: 'Hierarchical Grid Filtering', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-filtering-template': { displayName: 'Hierarchical Grid Filtering Template', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-excel-style-filtering-sample-1': { displayName: 'Hierarchical Grid Excel Style Filtering', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-excel-style-filtering-sample-2': { displayName: 'Hierarchical Grid Excel Style Filtering Operations', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-excel-style-filtering-sample-3': { displayName: 'Hierarchical Grid Excel Style Filtering Templates', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-excel-style-filtering-load-on-demand': { displayName: 'Hierarchical Grid Excel Style Filtering Load On Demand', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-excel-style-filtering-style': { displayName: 'Hierarchical Grid Excel Style Filtering Styling', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-external-excel-style-filtering': { displayName: 'Hierarchical Grid External Excel Style Filtering', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-excel-export': { displayName: 'Hierarchical Grid Excel Export', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-external-advanced-filtering': { displayName: 'Hierarchical Grid External Advanced Filtering', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-external-outlet': { displayName: 'Hierarchical Grid External Outlet', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-custom-filtering': { displayName: 'Hierarchical Grid Custom Filtering', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-sorting': { displayName: 'Hierarchical Grid Sorting', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-sorting-styling': { displayName: 'Hierarchical Grid Sorting Styling', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-selection': { displayName: 'Hierarchical Grid Selection', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-selection-template-numbers': { displayName: 'Hierarchical Grid Row Selectors Template - Numbers', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-styling': { displayName: 'Hierarchical Grid Styling', parentName: 'Hierarchical Grid'},
    'hierarchical-grid-summary': { displayName: 'Hierarchical Grid Summary', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-summary-styling': { displayName: 'Hierarchical Grid Summary Styling', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-paging': { displayName: 'Hierarchical Grid Paging', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-remote-paging': { displayName: 'Hierarchical Grid Remote Paging', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-reusable-paginator': { displayName: 'Hierarchical Grid Reusable Paginator', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-density': { displayName: 'Hierarchical Grid Display Density', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-moving': { displayName: 'Hierarchical Grid Column Moving', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-moving-styled': { displayName: 'Hierarchical Grid Column Moving Styled', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-pinning': { displayName: 'Hierarchical Grid Header Template with Pinning', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-toolbar-pinning': { displayName: 'Hierarchical Grid Toolbar Pinning', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-resize-line-styling': { displayName: 'Hierarchical Grid Resize Line Styling', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-hiding': { displayName: 'Hierarchical Grid Column Hiding', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-custom-hiding': { displayName: 'Hierarchical Grid Custom Hiding', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-multi-cell-style': { displayName: 'Hierarchical Grid Multi Cell Selection Style', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-toolbar-title': { displayName: 'Hierarchical Grid Toolbar Title', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-toolbar-options': { displayName: 'Hierarchical Grid Toolbar Options', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-toolbar-custom': { displayName: 'Hierarchical Grid Toolbar Custom Content', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-lod': { displayName: 'Hierarchical Grid Load on Demand', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-custom-kb-navigation': { displayName: 'Hierarchical Grid Custom Keyboard Navigation', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-disable-summaries': { displayName: 'Hierarchical Grid Disable Summaries', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-paging-style': { displayName: 'HGrid Paging Style', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-column-hiding-style': { displayName: 'HGrid Column Hiding Style', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-multi-column': { displayName: 'Hierarchical Grid Multi Column Headers', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-multi-column-template': { displayName: 'Hierarchical Grid Multi Column Header Template', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-multi-column-styling': { displayName: 'Hierarchical Grid Multi Column Header Styling', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-multi-column-export': { displayName: 'Hierarchical Grid Multi Column Headers Export', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-row-edit-style': { displayName: 'HGrid Row Edit Style', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-row-pinning': { displayName: 'Hierarchical Grid Row Pinning', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-row-pinning-styling': { displayName: 'Hierarchical Grid Row Pinning Styling', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-row-pinning-extra-column': { displayName: 'Hierarchical Grid Row Pinning Custom UI', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-toolbar-style': { displayName: 'HGrid Toolbar Style', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-add-row': { displayName: 'Hierarchical Grid Add Row', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-advanced-filtering': { displayName: 'Hierarchical Grid Advanced Filtering', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-advanced-filtering-style': { displayName: 'Hierarchical Grid Advanced Filtering Style', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-filtering-style': { displayName: 'HGrid Filtering Style', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-conditional-row-selectors': { displayName: 'HGrid Conditional Row Selectors', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-collapsible-column-groups': { displayName: 'HGrid Collapsible Column Grous', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-allData-summary': {displayName: 'HGrid All Data Custom Summaries', parentName: 'Hierarchical Grid'},
    'hierarchical-grid-validation-style': { displayName: 'Hierarchical Grid Validation Style', parentName: 'Hierarchical Grid' },
    'hgrid-summary-template': {displayName: 'HGrid Summary Template', parentName: 'Hierarchical Grid'},
    'hierarchical-grid-sample-right-pinning': { displayName: 'Hierarchical Grid Right Side Pinning', parentName: 'Hierarchical Grid' },
    'column-selection': { displayName: 'HGrid Column Selection', parentName: 'Hierarchical Grid' },
    'column-group-selection': { displayName: 'HGrid Column Group Selection', parentName: 'Hierarchical Grid' },
    'column-selection-styles': { displayName: 'HGrid Column Selection Styles', parentName: 'Hierarchical Grid' },
    'hgrid-keyboard-guide': { displayName: 'HGrid Keyboard navigation guide', parentName: 'Hierarchical Grid' },
    'remote-paging-default-template': { displayName: 'HGrid remote paging with default template', parentName: 'Hierarchical Grid' },
    'hGrid-state': { displayName: 'HGrid Save State', parentName: 'Hierarchical Grid' },
    'hGrid-state-about': { displayName: 'HGrid About', parentName: 'Hierarchical Grid' },
    'hGrid-editing-lifecycle': { displayName: 'Hierarchical Grid Editing lifecycle', parentName: 'Hierarchical Grid' },
    'hGrid-cell-selection': {displayName: 'HGrid Cell Selection', parentName: 'Hierarchical Grid'},
    'hGrid-formatted-filtering-strategy': { displayName: 'HGrid Formatted Filtering Strategy', parentName: 'Hierarchical Grid' },
    'hGrid-summary-formatter': { displayName: 'HGrid Summary Formatter', parentName: 'Hierarchical Grid' },
    'hGrid-row-classes': { displayName: 'HGrid RowClasses', parentName: 'Hierarchical Grid' },
    'hGrid-row-styles': { displayName: 'HGrid RowStyles', parentName: 'Hierarchical Grid' },
    'hGrid-action-strip': { displayName: 'HGrid with Action Strip', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-validator-service': { displayName: 'Hierarchical Grid Validator Service', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-validator-service-extended': { displayName: 'Hierarchical Grid Validator Service Extended', parentName: 'Hierarchical Grid' },
    'hGrid-columnAutosizing-sample': { displayName: 'HGrid Column Autosizing Sample', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-cross-field-validation': { displayName: 'Hierarchical Grid Cross-field Validation', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-summary-export': { displayName: 'Hierarchical Grid Summary Export', parentName: 'Hierarchical Grid' },
    'hierarchical-grid-both-sides-pinning': { displayName: 'Hierarchical Grid Both Sides Pinning', parentName: 'Hierarchical Grid' }
};
