// tslint:disable:object-literal-sort-keys

export const interactionsRoutesData = {
    'chat-overview-sample': { displayName: 'Chat Overview', parentName: 'Chat' },
    'chat-features-sample': { displayName: 'Chat Features', parentName: 'Chat' },
    'chat-styling-sample': { displayName: 'Chat Styling', parentName: 'Chat' },
    'dialog-sample-1': { displayName: 'Completed Action Dialog', parentName: 'Dialog' },
    'dialog-sample-2': { displayName: 'Confirmation Dialog', parentName: 'Dialog' },
    'dialog-sample-3': { displayName: 'Sign-in form Dialog', parentName: 'Dialog' },
    'dialog-styling-sample': {displayName: 'Dialog Styling', parentName: 'Dialog' },
    'slider-sample-1': { displayName: 'Slider Lower and Upper range values', parentName: 'Slider' },
    'slider-sample-2': { displayName: 'Continuous Slider', parentName: 'Slider' },
    'slider-sample-3': { displayName: 'Discrete Slider', parentName: 'Slider' },
    'slider-sample-4': { displayName: 'Range Slider', parentName: 'Slider' },
    'slider-sample-5': { displayName: 'Slider Lower and Upper bounds', parentName: 'Slider' },
    'slider-sample-6': { displayName: 'Slider Labels', parentName: 'Slider' },
    'slider-secondary-ticks-mirror': { displayName: 'Slider Secondary Ticks Mirror', parentName: 'Slider' },
    'discrete-slider-ticks-bottom': { displayName: 'Discret Slider Ticks Bottom', parentName: 'Slider' },
    'slider-ticks-bottomtotop-labels': { displayName: 'Slider Ticks Bottomtotop Labels', parentName: 'Slider' },
    'slider-primary-ticks-top': { displayName: 'Slider Primary Ticks Top', parentName: 'Slider' },
    'slider-timeframe': { displayName: 'Slider Timeframe', parentName: 'Slider' },
    'slider-tick-labels-template': { displayName: 'Slider Tick labels template', parentName: 'Slider' },
    'slider-styling-sample': { displayName: 'Slider styling sample', parentName: 'Slider' },
    'slider-tailwind-styling-sample': { displayName: 'Slider tailwind styling sample', parentName: 'Slider' },
    'ripple-sample-2': { displayName: 'Ripple Target', parentName: 'Ripple' },
    'ripple-sample-3': { displayName: 'Ripple Centered Effect', parentName: 'Ripple' },
    'ripple-sample-4': { displayName: 'Ripple Duration', parentName: 'Ripple' },
    'ripple-sample-5': { displayName: 'Ripple Effect', parentName: 'Ripple' },
    'ripple-sample-6': { displayName: 'Ripple Color', parentName: 'Ripple' },
    'ripple-styling': { displayName: 'Ripple Styling', parentName: 'Ripple' },
    // eslint-disable-next-line quote-props
    'toggle': { displayName: 'Toggle Overview', parentName: 'Toggle' },
    'toggle-sample-1': { displayName: 'Toggle Content', parentName: 'Toggle' },
    'toggle-sample-2': { displayName: 'Automatic Toggle Actions', parentName: 'Toggle' },
    'toggle-sample-3': { displayName: 'Toggle Service Provider', parentName: 'Toggle' },
    'toggle-sample-4': { displayName: 'Offset Toggle', parentName: 'Toggle' },
    'tooltip-simple': { displayName: 'Simple Tooltip', parentName: 'Tooltip' },
    'tooltip-rich': { displayName: 'Rich Tooltip', parentName: 'Tooltip' },
    'tooltip-style': { displayName: 'Tooltip Style', parentName: 'Tooltip' },
    'tooltip-tailwind-style': { displayName: 'Tooltip Tailwind Style', parentName: 'Tooltip' },
    'overlay-sample-main-1': { displayName: 'Overlay Main Sample 1', parentName: 'Overlay' },
    'overlay-sample-main-2': { displayName: 'Overlay Main Sample 2', parentName: 'Overlay' },
    'overlay-sample-main-3': { displayName: 'Overlay Main Sample 3', parentName: 'Overlay' },
    'overlay-position-sample-1': { displayName: 'Overlay Position Sample 1', parentName: 'Overlay' },
    'overlay-position-sample-2': { displayName: 'Overlay Position Sample 2', parentName: 'Overlay' },
    'overlay-position-sample-3': { displayName: 'Overlay Position Sample 3', parentName: 'Overlay' },
    'overlay-preset-settings-sample': { displayName: 'Preset Overlay Settings', parentName: 'Overlay' },
    'overlay-scroll-sample-1': { displayName: 'Overlay Scroll Sample 1', parentName: 'Overlay' },
    'overlay-scroll-sample-2': { displayName: 'Overlay Scroll Sample 2', parentName: 'Overlay' },
    'overlay-styling-simple': { displayName: 'Overlay Styling', parentName: 'Overlay'},
    'email-sample': { displayName: 'Email sample', parentName: 'Drag and Drop' },
    'kanban-sample': { displayName: 'Kanban sample', parentName: 'Drag and Drop' },
    'list-reorder-sample': { displayName: 'List Reorder sample', parentName: 'Drag and Drop' },
    'drag-dialog-sample': { displayName: 'Drag Dialog Sample', parentName: 'Drag and Drop'},
    'icons-sample': { displayName: 'Icons sample', parentName: 'Drag and Drop' },
    'query-builder-sample-1': { displayName: 'Query Builder Sample 1', parentName: 'Query Builder' },
    'query-builder-style': { displayName: 'Query Builder Style Sample', parentName: 'Query Builder' },
    'query-builder-tailwind-style': { displayName: 'Query Builder Tailwind Style Sample', parentName: 'Query Builder' },
    'query-builder-template-sample': { displayName: 'Query Builder Template Sample', parentName: 'Query Builder' },
    'query-builder-sql-sample': { displayName: 'Query Builder SQL Sample', parentName: 'Query Builder' },
    'query-builder-request-sample': { displayName: 'Query Builder Request Sample', parentName: 'Query Builder' }
};
