// tslint:disable:object-literal-sort-keys

export const interactionsRoutesData = {
    "dialog": { displayName: "Various Dialogs", parentName: "Dialog" },
    "dialog-sample-1": { displayName: "Completed Action Dialog", parentName: "Dialog" },
    "dialog-sample-2": { displayName: "Confirmation Dialog", parentName: "Dialog" },
    "dialog-sample-3": { displayName: "Sign-in form Dialog", parentName: "Dialog" },
    "slider-sample-1": { displayName: "Slider Lower and Upper range values", parentName: "Slider" },
    "slider-sample-2": { displayName: "Continuous Slider", parentName: "Slider" },
    "slider-sample-3": { displayName: "Discrete Slider", parentName: "Slider" },
    "slider-sample-4": { displayName: "Range Slider", parentName: "Slider" },
    "slider-sample-5": { displayName: "Slider Lower and Upper bounds", parentName: "Slider" },
    "ripple-sample-1": { displayName: "Ripple Overview", parentName: "Ripple" },
    "ripple-sample-2": { displayName: "Ripple Target", parentName: "Ripple" },
    "ripple-sample-3": { displayName: "Ripple Centered Effect", parentName: "Ripple" },
    "ripple-sample-4": { displayName: "Ripple Duration", parentName: "Ripple" },
    "ripple-sample-5": { displayName: "Ripple Effect", parentName: "Ripple" },
    "ripple-sample-6": { displayName: "Ripple Color", parentName: "Ripple" },
    "toggle": { displayName: "Toggle Overview", parentName: "Toggle" },
    "toggle-sample-1": { displayName: "Toggle Content", parentName: "Toggle" },
    "toggle-sample-2": { displayName: "Automatic Toggle Actions", parentName: "Toggle" },
    "toggle-sample-3": { displayName: "Toggle Service Provider", parentName: "Toggle" },
    "tooltip-simple": { displayName: "Simple Tooltip", parentName: "Tooltip" },
    "tooltip-rich": { displayName: "Rich Tooltip", parentName: "Tooltip" },
    "overlay-sample-main-1": { displayName: "Overlay Main Sample 1", parentName: "Overlay" },
    "overlay-sample-main-2": { displayName: "Overlay Main Sample 2", parentName: "Overlay" },
    "overlay-sample-main-3": { displayName: "Overlay Main Sample 3", parentName: "Overlay" },
    "overlay-position-sample-1": { displayName: "Overlay Position Sample 1", parentName: "Overlay" },
    "overlay-position-sample-2": { displayName: "Overlay Position Sample 2", parentName: "Overlay" },
    "overlay-scroll-sample-1": { displayName: "Overlay Scroll Sample 1", parentName: "Overlay" },
    "overlay-scroll-sample-2": { displayName: "Overlay Scroll Sample 2", parentName: "Overlay" },
    "drag-drop-sample": { displayName: "Drag and drop sample", parentName: "Drag and Drop" }
};
