export const DATA: any[] = [
    {
        Address: "Obere Str. 57",
        City: "Berlin",
        CompanyName: "Alfreds Futterkiste",
        ContactName: "Maria Anders",
        ContactTitle: "Sales Representative",
        Country: "Germany",
        Fax: "030-0076545",
        ID: "ALFKI",
        Phone: "030-0074321",
        PostalCode: "12209",
        Region: null
    },
    {
        Address: "Avda. de la Constitución 2222",
        City: "México D.F.",
        CompanyName: "Ana Trujillo Emparedados y helados",
        ContactName: "Ana Trujillo",
        ContactTitle: "Owner",
        Country: "Mexico",
        Fax: "(5) 555-3745",
        ID: "ANATR",
        Phone: "(5) 555-4729",
        PostalCode: "05021",
        Region: null
    },
    {
        Address: "Mataderos 2312",
        City: "México D.F.",
        CompanyName: "Antonio Moreno Taquería",
        ContactName: "Antonio Moreno",
        ContactTitle: "Owner",
        Country: "Mexico",
        Fax: null,
        ID: "ANTON",
        Phone: "(5) 555-3932",
        PostalCode: "05023",
        Region: null
    },
    {
        Address: "120 Hanover Sq.",
        City: "London",
        CompanyName: "Around the Horn",
        ContactName: "Thomas Hardy",
        ContactTitle: "Sales Representative",
        Country: "UK",
        Fax: "(171) 555-6750",
        ID: "AROUT",
        Phone: "(171) 555-7788",
        PostalCode: "WA1 1DP",
        Region: null
    },
    {
        Address: "Berguvsvägen 8",
        City: "Luleå",
        CompanyName: "Berglunds snabbköp",
        ContactName: "Christina Berglund",
        ContactTitle: "Order Administrator",
        Country: "Sweden",
        Fax: "0921-12 34 67",
        ID: "BERGS",
        Phone: "0921-12 34 65",
        PostalCode: "S-958 22",
        Region: null
    },
    {
        Address: "Forsterstr. 57",
        City: "Mannheim",
        CompanyName: "Blauer See Delikatessen",
        ContactName: "Hanna Moos",
        ContactTitle: "Sales Representative",
        Country: "Germany",
        Fax: "0621-08924",
        ID: "BLAUS",
        Phone: "0621-08460",
        PostalCode: "68306",
        Region: null
    },
    {
        Address: "24, place Kléber",
        City: "Strasbourg",
        CompanyName: "Blondesddsl père et fils",
        ContactName: "Frédérique Citeaux",
        ContactTitle: "Marketing Manager",
        Country: "France",
        Fax: "88.60.15.32",
        ID: "BLONP",
        Phone: "88.60.15.31",
        PostalCode: "67000",
        Region: null
    },
    {
        Address: "C/ Araquil, 67",
        City: "Madrid",
        CompanyName: "Bólido Comidas preparadas",
        ContactName: "Martín Sommer",
        ContactTitle: "Owner",
        Country: "Spain",
        Fax: "(91) 555 91 99",
        ID: "BOLID",
        Phone: "(91) 555 22 82",
        PostalCode: "28023",
        Region: null
    },
    {
        Address: "12, rue des Bouchers",
        City: "Marseille",
        CompanyName: "Bon app'",
        ContactName: "Laurence Lebihan",
        ContactTitle: "Owner",
        Country: "France",
        Fax: "91.24.45.41",
        ID: "BONAP",
        Phone: "91.24.45.40",
        PostalCode: "13008",
        Region: null
    },
    {
        Address: "23 Tsawassen Blvd.",
        City: "Tsawassen",
        CompanyName: "Bottom-Dollar Markets",
        ContactName: "Elizabeth Lincoln",
        ContactTitle: "Accounting Manager",
        Country: "Canada",
        Fax: "(604) 555-3745",
        ID: "BOTTM",
        Phone: "(604) 555-4729",
        PostalCode: "T2F 8M4",
        Region: "BC"
    },
    {
        Address: "Fauntleroy Circus",
        City: "London",
        CompanyName: "B's Beverages",
        ContactName: "Victoria Ashworth",
        ContactTitle: "Sales Representative",
        Country: "UK",
        Fax: null,
        ID: "BSBEV",
        Phone: "(171) 555-1212",
        PostalCode: "EC2 5NT",
        Region: null
    },
    {
        Address: "Cerrito 333",
        City: "Buenos Aires",
        CompanyName: "Cactus Comidas para llevar",
        ContactName: "Patricio Simpson",
        ContactTitle: "Sales Agent",
        Country: "Argentina",
        Fax: "(1) 135-4892",
        ID: "CACTU",
        Phone: "(1) 135-5555",
        PostalCode: "1010",
        Region: null
    },
    {
        Address: "Sierras de Granada 9993",
        City: "México D.F.",
        CompanyName: "Centro comercial Moctezuma",
        ContactName: "Francisco Chang",
        ContactTitle: "Marketing Manager",
        Country: "Mexico",
        Fax: "(5) 555-7293",
        ID: "CENTC",
        Phone: "(5) 555-3392",
        PostalCode: "05022",
        Region: null
    },
    {
        Address: "Hauptstr. 29",
        City: "Bern",
        CompanyName: "Chop-suey Chinese",
        ContactName: "Yang Wang",
        ContactTitle: "Owner",
        Country: "Switzerland",
        Fax: null,
        ID: "CHOPS",
        Phone: "0452-076545",
        PostalCode: "3012",
        Region: null
    },
    {
        Address: "Av. dos Lusíadas, 23",
        City: "Sao Paulo",
        CompanyName: "Comércio Mineiro",
        ContactName: "Pedro Afonso",
        ContactTitle: "Sales Associate",
        Country: "Brazil",
        Fax: null,
        ID: "COMMI",
        Phone: "(11) 555-7647",
        PostalCode: "05432-043",
        Region: "SP"
    },
    {
        Address: "Berkeley Gardens 12 Brewery",
        City: "London",
        CompanyName: "Consolidated Holdings",
        ContactName: "Elizabeth Brown",
        ContactTitle: "Sales Representative",
        Country: "UK",
        Fax: "(171) 555-9199",
        ID: "CONSH",
        Phone: "(171) 555-2282",
        PostalCode: "WX1 6LT",
        Region: null
    }
];
