/*eslint-disable*/

export const dataDisplayRoutesData = {
    "badge-icon": { displayName: "Badge Icon Sample", parentName: "Badge" },
    "badge-overview": { displayName: "Overview", parentName: "Badge" },
    "badge-size": { displayName: "Badge Size", parentName: "Badge" },
    "badge-type": { displayName: "Badge Type", parentName: "Badge" },
    "badge-shape": { displayName: "Badge Shape", parentName: "Badge" },
    "badge-variants": { displayName: "Badge Variants", parentName: "Badge" },
    "badge-outlined": { displayName: "Badge Outlined", parentName: "Badge" },
    "badge-dot": { displayName: "Badge Dot", parentName: "Badge" },
    "badge-styling": { displayName: "Badge Styling", parentName: "Badge" },
    "badge-tailwind-styling": { displayName: "Badge Tailwind Styling", parentName: "Badge" },
    "chip-simple": { displayName: "Chip Simple", parentName: "Chip" },
    "chip-outlined": { displayName: "Chip Outlined", parentName: "Chip" },
    "chip-variants": { displayName: "Chip Variants", parentName: "Chip" },
    "chip-area-sample": { displayName: "Chip Area Sample", parentName: "Chip" },
    "chip-styling": { displayName: "Chip Styling", parentName: "Chip" },
    "chip-tailwind-styling": { displayName: "Chip Tailwind Styling", parentName: "Chip" },
    "circular-progressbar": { displayName: "Circular Progressbar Sample", parentName: "Circular Progressbar" },
    "circular-dynamic-sample": { displayName: "Circular Dynamic Sample", parentName: "Circular Progressbar" },
    // tslint:disable-next-line:max-line-length
    "circular-indeterminate-progressbar": { displayName: "Circular Indeterminate Progressbar", parentName: "Circular Progressbar" },
    "circular-styling-sample": { displayName: "Circular Styling Sample", parentName: "Circular Progressbar" },
    "icon-sample-1": { displayName: "Simple Icons", parentName: "Icon" },
    "icon-service": { displayName: "Icon Service", parentName: "Icon" },
    "icon-styling": { displayName: "Icon Styling", parentName: "Icon" },
    "icon-tailwind-styling": { displayName: "Icon Tailwind Styling", parentName: "Icon" },
    "svg-icon-sample": { displayName: "SVG Icons", parentName: "Icon" },
    "material-symbols": { displayName: "Material Symbols", parentName: "Icon" },
    "material-icons-extended": { displayName: "Material Icons Extended", parentName: "Icon" },
    "igx-for-sample-1": { displayName: "List with igxFor directive", parentName: "For" },
    "igx-for-sample-2": { displayName: "IgxFor Horizontal virtualization", parentName: "For" },
    "linear-dynamic-sample": { displayName: "Dynamic Linear Progressbar", parentName: "Linear Progressbar" },
    "linear-progressbar": { displayName: "Simple Linear Progressbar", parentName: "Linear Progressbar" },
    "linear-progressbar-sample-1": { displayName: "Linear Progressbar Types", parentName: "Linear Progressbar" },
    "linear-progressbar-sample-2": { displayName: "Linear Progressbar Styles", parentName: "Linear Progressbar" },
    "linear-progressbar-styling": { displayName: "Linear Progressbar Styling", parentName: "Linear Progressbar" },
    "mask-sample-1": { displayName: "Mask Overview", parentName: "Mask" },
    "mask-sample-2": { displayName: "Mask on Input", parentName: "Mask" },
    "mask-sample-3": { displayName: "Mask binding to Formatted/Raw Value", parentName: "Mask" },
    "mask-sample-4": { displayName: "Additional custom formatting", parentName: "Mask" },
    "mask-sample-5": { displayName: "Placeholder", parentName: "Mask" },
    "text-highlight-1": { displayName: "Search within a single container", parentName: "Text Highlight" },
    "text-highlight-2": { displayName: "Search within multiple containers", parentName: "Text Highlight" },
    "text-highlight-style": { displayName: "Text Highlight Style", parentName: "Text Highlight" }
};
