/*eslint-disable*/

export const dataEntriesRoutesData = {
    "autocomplete": { displayName: "Autocomplete", parentName: "Autocomplete" },
    "movie": { displayName: "Movie Availability", parentName: "Autocomplete" },
    "button-group-sample-1": { displayName: "Button Group Overview", parentName: "Button Group" },
    "button-group-sample-2": { displayName: "Vertical Button Group", parentName: "Button Group" },
    "button-group-sample-3": { displayName: "Horizontal Button Group", parentName: "Button Group" },
    "button-group-sample-4": { displayName: "Selection Mode", parentName: "Button Group" },
    "button-group-sample-5": { displayName: "Display Density", parentName: "Button Group" },
    "button-group-style": { displayName: "Button Group Style", parentName: "Button Group" },
    "button-group-tailwind-style": { displayName: "Button Group Tailwind Style", parentName: "Button Group" },
    "buttons-sample-1": { displayName: "Overview", parentName: "Buttons" },
    "buttons-sample-2": { displayName: "Flat Button", parentName: "Buttons" },
    "buttons-sample-3": { displayName: "Button Ripple", parentName: "Buttons" },
    "buttons-sample-4": { displayName: "Span Button", parentName: "Buttons" },
    "buttons-sample-5": { displayName: "Contained Button", parentName: "Buttons" },
    "buttons-sample-6": { displayName: "Floating Action Button", parentName: "Buttons" },
    "buttons-sample-7": { displayName: "Icon Button", parentName: "Buttons" },
    "buttons-sample-8": { displayName: "Outlined Button", parentName: "Buttons" },
    "buttons-disabled-sample": { displayName: "Disabled Button", parentName: "Buttons" },
    "buttons-display-density": { displayName: "Display Density", parentName: "Buttons" },
    "buttons-roundness-sample": { displayName: "Components Roundness", parentName: "Buttons" },
    "buttons-style": { displayName: "Button Style", parentName: "Buttons" },
    "buttons-tailwind-style": { displayName: "Button Tailwind Style", parentName: "Buttons" },
    "checkbox-sample-1": { displayName: "Simple Checkbox", parentName: "Checkbox" },
    "checkbox-sample-2": { displayName: "Multiple Checkboxes", parentName: "Checkbox" },
    "checkbox-sample-3": { displayName: "Indeterminate Checkbox", parentName: "Checkbox" },
    "checkbox-styling": { displayName: "Checkbox Styling", parentName: "Checkbox" },
    "checkbox-tailwind-styling": { displayName: "Checkbox Tailwind Styling", parentName: "Checkbox" },
    "dropdown-remote": { displayName: "Virtual Dropdown - Remote Data", parentName: "Dropdown" },
    "dropdown-virtual": { displayName: "Virtual Dropdown", parentName: "Dropdown" },
    "dropdown-menu": { displayName: "Dropdown as Menu", parentName: "Dropdown" },
    "dropdown-multi-level-menu": { displayName: "Multi-Level Dropdown Menu", parentName: "Dropdown" },
    "dropdown-sample-1": { displayName: "Simple Dropdown", parentName: "Dropdown" },
    "dropdown-sample-2": { displayName: "Dropdown Selection", parentName: "Dropdown" },
    "dropdown-sample-3": { displayName: "Dropdown Headers", parentName: "Dropdown" },
    "dropdown-sample-5": { displayName: "Dropdown Groups", parentName: "Dropdown" },
    "dropdown-styling": { displayName: "Dropdown Styling", parentName: "Dropdown" },
    "dropdown-tree-hierarchical-selection": { displayName: "Dropdown Tree Hierarchical Selection", parentName: "Dropdown" },
    "dropdown-tree-grid-hierarchical-selection": { displayName: "Dropdown Tree Grid Hierarchical Selection", parentName: "Dropdown" },
    "dropdown-sample-4": { displayName: "Input Dropdown Selection", parentName: "Dropdown" },
    "icon-button-overview": { displayName: "Overview", parentName: "Icon Buttons" },
    "flat-icon-button": { displayName: "Flat Icon Button", parentName: "Icon Buttons" },
    "contained-icon-button": { displayName: "Contained Icon Button", parentName: "Icon Buttons" },
    "outlined-icon-button": { displayName: "Outlined Icon Button", parentName: "Icon Buttons" },
    "disabled-icon-button": { displayName: "Disabled Icon Button", parentName: "Icon Buttons" },
    "svg-icon-button": { displayName: "SVG Icon Button", parentName: "Icon Buttons" },
    "icon-button-size": { displayName: "Icon Button Size", parentName: "Icon Buttons" },
    "icon-button-styling": { displayName: "Icon Button Styling", parentName: "Icon Buttons" },
    "icon-button-tailwind-styling": { displayName: "Icon Button Tailwind Styling", parentName: "Icon Buttons" },
    "input-group-sample-1": { displayName: "Simple Input Group", parentName: "Input Group" },
    "input-group-sample-2": { displayName: "Input Required", parentName: "Input Group" },
    "input-group-sample-3": { displayName: "Input Group Prefix and Sufix", parentName: "Input Group" },
    "input-group-sample-4": { displayName: "Input Group Hint", parentName: "Input Group" },
    "input-group-sample-5": { displayName: "Input Group Types", parentName: "Input Group" },
    "input-group-sample-6": { displayName: "Input Group Full Form", parentName: "Input Group" },
    "input-group-style": { displayName: "Input Group Style", parentName: "Input Group" },
    "input-group-tailwind-style": { displayName: "Input Group Tailwind Style", parentName: "Input Group" },
    "reactive-forms": { displayName: "Reactive Forms Overview", parentName: "Angular Reactive Forms" },
    "radio-sample-1": { displayName: "Simple Radio Buttons", parentName: "Radio" },
    "radio-sample-2": { displayName: "Radio Button Binding", parentName: "Radio" },
    "radio-sample-3": { displayName: "Radio Label Position", parentName: "Radio" },
    "radio-group-sample": { displayName: "Radio Group", parentName: "Radio" },
    "radio-group-vertical": { displayName: "Vertical Radio Group", parentName: "Radio" },
    "radio-styling-sample": { displayName: "Styling Radio Buttons", parentName: "Radio" },
    "radio-tailwind-styling-sample": { displayName: "Tailwind Styling Radio Buttons", parentName: "Radio" },
    "rating-form": { displayName: "Rating in Form", parentName: "Rating" },
    "switch-sample-1": { displayName: "Switch Overview", parentName: "Switch" },
    "switch-sample-2": { displayName: "Multiple Switches", parentName: "Switch" },
    "switch-styling": { displayName: "Styled Switches", parentName: "Switch" },
    "switch-tailwind-styling": { displayName: "Tailwind Styled Switches", parentName: "Switch" },
    "select-sample-1": { displayName: "Simple Select", parentName: "Select" },
    "select-sample-2": { displayName: "Select With Groups", parentName: "Select" },
    "select-sample-4": { displayName: "Custom Overlay Settings", parentName: "Select" },
    "select-styling": { displayName: "Select Styling", parentName: "Select" },
    "select-tailwind-styling": { displayName: "Select Tailwind Styling", parentName: "Select" },
    "select-input-directives": { displayName: "Select Input Directives", parentName: "Select" },
    "select-header-footer": { displayName: "Select with Header&Footer Templates", parentName: "Select" },
    "input-text-selection": { displayName: "Input with Text Selection", parentName: "Input Group" },
    "typed-form": { displayName: "Typed Form", parentName: "Input Group" },
    "template-driven-form-validation": { displayName: "Template Driven Form Validation", parentName: "Input Group" },
    "reactive-form-validation": { displayName: "Reactive Form Validation", parentName: "Input Group" },
    "reactive-form-custom-validation": { displayName: "Reactive Form Custom Validation", parentName: "Input Group" }
};
