// tslint:disable:object-literal-sort-keys

export const dataEntriesRoutesData = {
    "button-group-sample-1": { displayName: "Button Group Overview", parentName: "Button Group" },
    "button-group-sample-2": { displayName: "Vertical Button Group", parentName: "Button Group" },
    "button-group-sample-3": { displayName: "Horizontal Button Group", parentName: "Button Group" },
    "buttons-sample-1": { displayName: "Flat Buttons Overview", parentName: "Buttons" },
    "buttons-sample-2": { displayName: "Flat Button", parentName: "Buttons" },
    "buttons-sample-3": { displayName: "Flat Button Ripple Color", parentName: "Buttons" },
    "buttons-sample-4": { displayName: "Flat Button Ripple Color 2", parentName: "Buttons" },
    "buttons-sample-5": { displayName: "Raised Button", parentName: "Buttons" },
    "buttons-sample-6": { displayName: "Floating Action Button", parentName: "Buttons" },
    "buttons-sample-7": { displayName: "Icon Button", parentName: "Buttons" },
    "checkbox-sample-1": { displayName: "Simple Checkbox", parentName: "Checkbox" },
    "checkbox-sample-2": { displayName: "Multiple Checkboxes", parentName: "Checkbox" },
    "dropdown-menu": { displayName: "Dropdown as Menu", parentName: "Dropdown" },
    "dropdown-sample-1": { displayName: "Simple Dropdown", parentName: "Dropdown" },
    "dropdown-sample-2": { displayName: "Dropdown Selection", parentName: "Dropdown" },
    "dropdown-sample-3": { displayName: "Dropdown Headers", parentName: "Dropdown" },
    "dropdown-sample-4": { displayName: "Input Dropdown Selection", parentName: "Dropdown" },
    "input-group-sample-1": { displayName: "Simple Input Group", parentName: "Input Group" },
    "input-group-sample-2": { displayName: "Input Required", parentName: "Input Group" },
    "input-group-sample-3": { displayName: "Input Group Prefix and Sufix", parentName: "Input Group" },
    "input-group-sample-4": { displayName: "Input Group Hint", parentName: "Input Group" },
    "input-group-sample-5": { displayName: "Input Group Styling", parentName: "Input Group" },
    "input-group-sample-6": { displayName: "Input Group Full Form", parentName: "Input Group" },
    "reactive-forms": { displayName: "Reactive Forms Overview", parentName: "Reactive Forms" },
    "radio-sample-1": { displayName: "Simple Radio Buttons", parentName: "Radio" },
    "radio-sample-2": { displayName: "Radio Button Binding", parentName: "Radio" },
    "radio-group-sample": { displayName: "Radio Group", parentName: "Radio" },
    "switch-sample-1": { displayName: "Switch Overview", parentName: "Switch" },
    "switch-sample-2": { displayName: "Multiple Switches", parentName: "Switch" },
    "select-sample-1": { displayName: "Simple Select", parentName: "Select"},
    "select-sample-2": { displayName: "Select With Groups", parentName: "Select"},
    "select-sample-3": { displayName: "Select With Forms", parentName: "Select"}
};
