# This workflow will do a clean install of node dependencies, build the separate sample apps and lint them across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: IgniteUI Angular Samples CI

on:
  push:
    branches: [ master, vNext ]
  pull_request:
    branches: [ master, vNext ]

jobs:
  build-and-lint:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 14.x, 16.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
            node-version: ${{ matrix.node-version }}
            cache: 'npm'

      - name: Install packages
        run: npm ci

      - name: Lint
        run: npm run lint
      #  env:
      #      NODE_OPTIONS: --max_old_space_size=4096

      - name: Build
        run: npm run build
      #  env:
      #      NODE_OPTIONS: --max_old_space_size=4096

